Feature/apps 1592 edit study details
methodic-labs/chronicle-web pull request #12
Opened 2020-01-02 22:26 UTC by anzioka

2020-01-02 22:28 UTC, anzioka commented
Clean up study details page, enable updating of existing studies
<img width="1185" alt="study_details" src="https://user-images.githubusercontent.com/15723547/71697188-0e6d8d80-2d6c-11ea-9853-bcb2e73ed2c6.png">

2020-01-03 22:32 UTC, solomontang requested changes

2020-01-03 22:32 UTC, solomontang commented on src/containers/studies/components/CreateStudyForm.js
> +  }, [study]);
I would recommend moving this helper outside the scope of your component. This would still maintain reference equality without needing to spend resources on memoization, especially since it doesn't depend on any internal state.

```
const getInitialFormData(study) => {...}
...
const CreateStudyForm = (props :Props) => {
  useEffect(() => {
    if (editMode) {
      const formData :Object = getInitialFormData(study);
      setInitialFormData(formData);
    }
  }, [editMode, study])
// setInitialFormData is guaranteed by react to maintain reference equality
// getInitialFormData exists outside of the scope of the component and also does not need to be included as a dep
  ...
}
```

2020-01-03 22:32 UTC, solomontang commented on src/containers/study/StudyDetails.js
> +  };
There might be some flickering if you make the modal visible before resetting. Can you confirm?

2020-01-03 22:32 UTC, solomontang commented on src/containers/study/StudyDetailsContainer.js
> +  border-bottom: 2px solid #eee;
is there a suitable color in `NEUTRALS` you could use instead of #eeeeeee

2020-01-03 22:32 UTC, solomontang commented on src/containers/study/StudyDetailsContainer.js
> +  color: rgba(66, 66, 66, 0.7);
is there a suitable color in `NEUTRALS` you could use instead of this custom value?

2020-01-03 22:50 UTC, anzioka commented on src/containers/study/StudyDetails.js
> +  };
I didn't notice any flickering, but I will go ahead and reset state before displaying modal @solomontang

2020-01-04 01:31 UTC, UnsungHero97 requested changes

2020-01-04 01:31 UTC, UnsungHero97 commented on src/containers/study/StudyDetailsContainer.js
> +      </Card>
Why did you decide to not follow the UI pattern as is in the org details page in the orgs app?

2020-01-04 01:31 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +
What is your reasoning for moving this to the top? As far as I can tell, it doesn't change anything.

2020-01-04 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +            ? <span> Failed to updated study. Please try again. </span>
`updated` should be `update`.

2020-01-04 01:31 UTC, UnsungHero97 commented on src/containers/study/StudyDetails.js
> +          missingValue={!studyDescription || isEmptyString(studyDescription)}
You can simplify this to `missingValue={!isNonEmptyString(studyDescription)}`

2020-01-04 01:31 UTC, UnsungHero97 commented on src/containers/study/StudyDetails.js
> +          missingValue={!studyGroup || isEmptyString(studyGroup)}
You can simplify this to `missingValue={!isNonEmptyString(studyGroup)}`

2020-01-04 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +    editMode,
Do you really need this prop?

2020-01-04 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +  const requestState = editMode ? requestStates[UPDATE_STUDY] : requestStates[CREATE_STUDY];
Since you're reusing this modal to handle multiple cases, I recommend renaming it to something like `CreateOrEditStudyModal` or `StudyDetailsModal` or something along those lines.

2020-01-04 01:31 UTC, UnsungHero97 commented on src/containers/studies/StudiesContainer.js
> +        </Card>
Why are you wrapping everything inside a card? This looks weird:

![Screen Shot 2020-01-03 at 5 00 06 PM](https://user-images.githubusercontent.com/440299/71757408-84e0bd00-2e4a-11ea-9db4-559a7b2d0732.png)

2020-01-04 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyForm.js
> +  editMode :boolean;
Do you really need this prop?

2020-01-04 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyForm.js
> +};
I saw something very similar to this in the previous PR. Have you thought about how to construct the form data from a given entity in a way that is less manual?

2020-01-04 01:31 UTC, UnsungHero97 commented on src/containers/study/StudyDetails.js
> +const DetailContainer = styled.div`
We tend to use `Container` for components that are connected to the redux store.

2020-01-06 16:55 UTC, anzioka commented on src/containers/studies/components/CreateStudyForm.js
> +  editMode :boolean;
Yes I do @UnsungHero97. Using it to determine what action to dispatch / whether to initialize form with values.

2020-01-06 16:58 UTC, anzioka commented on src/containers/studies/components/CreateStudyModal.js
> +    editMode,
Yes I do. Same reason as posted here: https://github.com/Lattice-Works/chronicle/pull/12#discussion_r363382828

2020-01-06 17:11 UTC, anzioka commented on src/containers/studies/StudiesSagas.js
> +
Because the STUDY_ID value forms part of the name of the corresponding studyParticipantsEntitySetName

2020-01-06 17:13 UTC, anzioka commented on src/containers/study/StudyDetailsContainer.js
> +      </Card>
Please clarify what you mean @UnsungHero97 . Thanks.

2020-01-06 17:23 UTC, anzioka commented on src/containers/studies/StudiesContainer.js
> +        </Card>
Thought it would be a good idea to have a border around  the study cards.

This is what it really looks like: 
<img width="1055" alt="study_cards" src="https://user-images.githubusercontent.com/15723547/71835196-ce592400-3065-11ea-86b0-ce3caf210b93.png">

2020-01-06 19:28 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyForm.js
> +  editMode :boolean;
I see how you are using the prop and I understand why you introduced it. I'm asking whether or not it's actually necessary. I can think of at least one way to accomplish the same thing without having to rely on this prop.

2020-01-06 19:29 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +    editMode,
@anzioka I replied to your comment here: https://github.com/Lattice-Works/chronicle/pull/12#discussion_r363445629

2020-01-06 19:39 UTC, UnsungHero97 commented on src/containers/study/StudyDetailsContainer.js
> +      </Card>
Here's what I mean.

The organizations app layout is this:

![Screen Shot 2020-01-06 at 11 34 51 AM](https://user-images.githubusercontent.com/440299/71843395-a1fad300-3078-11ea-88c2-e2a84494ec2c.png)

The org title is at the top, followed by the various "tabs", followed by a "Card" with the content relevant to that tab.

What you have is quite different:

![Screen Shot 2020-01-06 at 11 34 57 AM](https://user-images.githubusercontent.com/440299/71843465-d2db0800-3078-11ea-8e95-1c2c5363efa1.png)

You have the title at the top, but the padding/margin is incorrect. Then, the "tabs" are inside the card and there's a border that shouldn't exist. Then, there's a green edit button. Then, you have dotted borders between the card segments. 

Why did you choose to not follow the orgs app design patterns?

2020-01-06 19:45 UTC, UnsungHero97 commented on src/containers/studies/StudiesContainer.js
> +        </Card>
Until our designers have bandwidth to redesign the app, please follow the existing design patterns.

2020-01-06 22:58 UTC, anzioka commented on src/containers/studies/StudiesContainer.js
> +        </Card>
Fixed. This is the new look.
<img width="1008" alt="study_cards" src="https://user-images.githubusercontent.com/15723547/71855045-d54b5b00-3094-11ea-8828-6a8d815ba9df.png">

2020-01-06 23:13 UTC, anzioka commented on src/containers/studies/components/CreateStudyForm.js
> +  editMode :boolean;
oh I see. I suppose I could use the study prop since the value will either be a map or undefined depending on whether we are editing an existing study or creating a new one, respectively.

2020-01-06 23:24 UTC, anzioka commented on src/containers/study/StudyDetailsContainer.js
> +      </Card>
It wasn't clear that the chronicle app should totally emulate the orgs app design patterns. I'll go ahead and make the changes though.

2020-01-07 00:30 UTC, anzioka commented on src/containers/study/StudyDetailsContainer.js
> +      </Card>
Most recent version: 
![Uploading study_details.png…]()

2020-01-07 00:41 UTC, UnsungHero97 approved these changes

2020-01-07 00:50 UTC, solomontang approved these changes

2020-01-07 00:50 UTC, merged