Task/apps 2070 create questionnaires
methodic-labs/chronicle-web pull request #123
Opened 2020-06-15 18:30 UTC by anzioka

PR:

1) Questionnaires dashboard. Display both active & inactive questionnaires in a table. Filter by active/inactive

2) Delete questionnaires and associated questions 

3) Toggle active status

4) Create questionnaire

<img width="1019" alt="dash" src="https://user-images.githubusercontent.com/15723547/86378211-416edc00-bc3e-11ea-8e53-7a2e43739a22.png">

<img width="1103" alt="delete" src="https://user-images.githubusercontent.com/15723547/86378291-59466000-bc3e-11ea-991a-b4f8a0f8b848.png">

![create](https://user-images.githubusercontent.com/15723547/86378344-695e3f80-bc3e-11ea-9609-b10bb8b9d0c7.gif)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15723547/86379267-7cbdda80-bc3f-11ea-89a4-dc798f43b82d.gif)

2020-06-19 21:14 UTC, UnsungHero97 requested changes

2020-06-19 21:14 UTC, UnsungHero97 commented on package.json
> +    "lattice-fabricate": "^0.13.1",
Please use `~`.

2020-06-19 21:14 UTC, UnsungHero97 commented on package.json
> +    "lattice-ui-kit": "^0.32.0",
Please use `~`.

2020-07-02 17:43 UTC, UnsungHero97 requested changes
Please capitalize the file names.

2020-07-02 21:49 UTC, solomontang commented
Any chance you could show us what the created questionnaire looks like? Also I'm noticing there isn't an "Edit" functionality. Is that coming in a future PR?

2020-07-02 22:20 UTC, anzioka commented
Here is a sample questionnaire:
<img width="1219" alt="Screen Shot 2020-07-02 at 3 18 46 PM" src="https://user-images.githubusercontent.com/15723547/86413936-6fbcdd80-bc77-11ea-81d1-d8513ed36adb.png">

2020-07-02 22:54 UTC, solomontang requested changes

2020-07-02 22:54 UTC, solomontang commented on src/containers/questionnaires/QuestionnairesContainer.js
> +  }, [studyQuestionnaires, studyEKID, dispatch]);
Will this run into an infinite loop of requests if getStudyQuestionnaires doesn't return any questionnaires? For example, what happens if there is a new study that doesn't have any questionnaires yet? Or if someone deletes a questionnaire to attempt to replace it?

2020-07-02 22:54 UTC, solomontang commented on src/containers/questionnaires/components/CreateQuestionnaireForm.js
> +  onExitEditMode :() => void;
From what I can tell, this is basically an onClose function. I'm not sure what "edit mode" is as it doesn't seem like you can edit existing questionnaires (only create, delete, and inactivate). If this is true, can you rename this prop?

2020-07-02 22:54 UTC, solomontang commented on src/containers/questionnaires/components/CreateQuestionnaireForm.js
> +        <Button onClick={onExitEditMode}> Cancel </Button>
Yeah, looks like invoking `onExitEditMode` is intended to just cancel creating a new questionnaire. Please rename to `onClose` or something that better represents what the function is doing.

2020-07-02 22:54 UTC, solomontang commented on src/containers/questionnaires/components/QuestionnairePreview.js
> +      <div style={{ paddingBottom: '20px' }}>
I get that inline styles are convenient especially for small changes like this, but it's prob best to stick to styled-components. Kind of strange to see some elements are using it but some are not. A little harder to see where some of the inline styles end since they're all just generic div tags as well.

A nitpick for sure.

2020-07-02 22:54 UTC, solomontang commented on src/containers/questionnaires/schemas/questionnaireSchema.js
> +        'ui:autofocus': true
I'd be careful with adding autofocus. Can have some intended behaviors when you're going back and forth between pages especially on mobile. Super annoying on mobile to have the on screen keyboard pop up all the time. Especially tricky since this is being on a list of items so it's possible for multiple elements per page to fight for focus.

2020-07-02 22:54 UTC, solomontang commented on src/containers/questionnaires/table/TableHeaderRow.js
> +              width={header.key} />
I suspect you mean to set the width to something other than the key which i believe it set to the following from https://github.com/Lattice-Works/chronicle/pull/123/files#diff-1af0a8e748242401224a609ed34e4cb0R39

```
const tableHeaders = ['title', 'status', 'actions'].map((header) => ({
  key: header,
  label: '',
  sortable: false
}));
```

2020-07-02 22:54 UTC, solomontang commented on src/containers/questionnaires/utils/index.js
> +};
There's some functionality built into luxon to do this for you. From any valid DateTime, you can access a series of properties like `.hour` and `.minute`

DateTime.local().hour

2020-07-03 00:21 UTC, anzioka commented on src/containers/questionnaires/QuestionnairesContainer.js
> +  }, [studyQuestionnaires, studyEKID, dispatch]);
No it won't run into an infinite loop. If the request doesn't return any data, then  studyQuestionnaires is just an empty immutable map and won't trigger subsequent renders + requests. Here is the view for a study that has no questionnaires.

<img width="1090" alt="Screen Shot 2020-07-02 at 5 16 14 PM" src="https://user-images.githubusercontent.com/15723547/86419582-7142d180-bc88-11ea-9f8c-3335118e3abe.png">

2020-07-03 00:28 UTC, anzioka commented on src/containers/questionnaires/components/QuestionnairePreview.js
> +      <div style={{ paddingBottom: '20px' }}>
Good point. Consistency

2020-07-03 00:54 UTC, anzioka commented on src/containers/questionnaires/schemas/questionnaireSchema.js
> +        'ui:autofocus': true
ah I hadn't thought about how this could impact user experience on mobile. I think the upside of autofocus is that it makes text inputting so much easier (at least on large screens). With autofocus, adding a new question is one click simpler. As for multiple views competing for focus, it seems to me, after several attempts, that the last view in the list will acquire focus on going back to previous page. That doesn't invalidate your point though haha.

It makes sense for this tool to be used primarily on large devices though, so maybe we could shrug off potential bad experience on mobile?

2020-07-03 01:22 UTC, anzioka commented on src/containers/questionnaires/table/TableHeaderRow.js
> +              width={header.key} />
I actually intent to set the width to the key.

The keys are mapped to widths in the getStyleVariation util:

https://github.com/Lattice-Works/chronicle/blob/e73748c41a19ac4f9171a812d40a06e2afead137/src/containers/questionnaires/QuestionnairesContainer.js#L63

```
const getWidthVariation = getStyleVariation('width', {
  default: 'auto',
  title: 'auto',
  status: '100px',
  actions: '110px'
});

const Cell = styled.td`
  width: ${getWidthVariation};
`;

type HeadCellProps = {
  width :string;
};

const HeadCell = ({ width } :HeadCellProps) => (
  <Cell width={width} />
);

```

2020-07-03 01:40 UTC, anzioka commented on src/containers/questionnaires/components/CreateQuestionnaireForm.js
> +  onExitEditMode :() => void;
renamed!

2020-07-03 05:12 UTC, anzioka commented
> Any chance you could show us what the created questionnaire looks like? Also I'm noticing there isn't an "Edit" functionality. Is that coming in a future PR?

Edit functionality is on its way in a separate PR :)

2020-07-08 19:34 UTC, UnsungHero97 requested changes

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaires/QuestionnairesContainer.js
> +                        headers={tableHeaders} />
Why did you go with `Table` here? This approach seems overly complicated and unnecessary.

1. the `Table` background does not respect the `Card` border radius:
<img width="284" alt="Screen Shot 2020-07-08 at 10 13 33 AM" src="https://user-images.githubusercontent.com/440299/86949599-c2791800-c103-11ea-96c3-eb764606ee48.png">

2. the `Table` does not respect the `CardSegment` padding:
<img width="1013" alt="Screen Shot 2020-07-08 at 10 05 28 AM" src="https://user-images.githubusercontent.com/440299/86949656-d45abb00-c103-11ea-9eb4-2f0bf1eae26f.png">

3. the `Table` header doesn't seem to be used, so there's unnecessary elements in the DOM that do nothing yet require computation from React.
<img width="922" alt="Screen Shot 2020-07-08 at 10 10 54 AM" src="https://user-images.githubusercontent.com/440299/86949921-416e5080-c104-11ea-9286-e433908b998c.png">

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireSagas.js
> +        }
I think this is a pattern that should be avoided as it can easily lead to preventable bugs.

What `changeActiveStatus` is REALLY doing is actually just setting the property value, i.e. `setActiveStatus`. As it is currently implemented, the actual logic for determining the value lives in 2 different places - `!activeStatus` is in the worker saga and in the reducer. 

For example, if `activeStatus` was a number instead of a boolean, you wouldn't want to do `activeStatus + 10` in multiple places. Or, if the logic for determining the `activeStatus` value was more complex, you wouldn't want to implement that in multiple places.

Further, the value for this particular property is strongly coupled with the user action. In other words, the value of `activeStatus` is directly controlled by the user's action. As such, I think `!activeStatus` should near the user action.

```
dispatch(
  setActiveStatus({
    questionnaireEKID,
    studyEKID,
    activeStatus: !activeStatus,
  })
);
```

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireSagas.js
> +      deleteType: DeleteTypes.HARD
My understanding is that `DeleteTypes.HARD` is for special cases. Let's discuss `SOFT` vs `HARD`.

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireSagas.js
> +function constructEntitiesFromFormData(formData, entityKeyIds, entitySetIds, propertyTypeIds :Map) {
This belongs in a `Utils` file, just like `createRecurrenceRuleSetFromFormData`.

2020-07-08 19:34 UTC, UnsungHero97 commented on src/core/edm/constants/FullyQualifiedNames.js
> +  COMPLETED_DATE_TIME_FQN: FQN.of('date.completeddatetime')
Please sort.

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireSagas.js
> +    formData = setIn(formData, [psk, eak], true);
This belongs in the schema as a default value, and you won't need these 2 lines.

```
[getEntityAddressKey(0, QUESTIONNAIRE_ES_NAME, ACTIVE_FQN)]: {
  default: true,
  type: 'boolean',
}
```

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireSagas.js
> +    LOG.error(action.type, error);
`LOG` before `yield`.

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireSagas.js
> +        mutator.set(neighborId, details.asImmutable());
You don't need to do the `asMutable()` / `asImmutable` dance.

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaires/components/CreateQuestionnaireForm.js
> +  }));
Don't return an object from `useSelector`.

```
const createQuestionnaireRS :?RequestState = useSelector(
  (state) => state.getIn(['questionnaire', CREATE_QUESTIONNAIRE, REQUEST_STATE])
);
```

Alternatively, you can use the `lattice-utils` helper:

```
import { useRequestState } from 'lattice-utils';
const createQuestionnaireRS :?RequestState = useRequestState(['questionnaire', CREATE_QUESTIONNAIRE]);
```

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaires/components/DeleteQuestionnaireModal.js
> +export default React.memo<Props>(DeleteQuestionnaireModal);
Why `React.memo`?

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaires/constants/constants.js
> +};
Unless there's some special logic for this, I recommend using luxon directly:

https://moment.github.io/luxon/docs/class/src/info.js~Info.html#static-method-weekdays

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaires/constants/questionTypes.js
> +  MULTIPLE_CHOICE:'Multiple choice';
Formatting... space before `:`.

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaires/constants/questionTypes.js
> +  MULTIPLE_CHOICE:'Multiple choice';
Please sort.

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaires/constants/questionTypes.js
> +  MULTIPLE_CHOICE: 'Multiple choice'
Please sort.

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaires/constants/questionnaireStatus.js
> +  NOT_ACTIVE:'NOT_ACTIVE';
Formatting... space before `:`

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaires/constants/constants.js
> +};
Ok, I think I have a simpler alternative...

In the `schedulerSchema`, use `enum` for the value and `enumNames` for the label:

```
import { Info } from 'luxon';
items: {
  enum: [RRule.MO, RRule.TU, RRule.WE, RRule.TH, RRule.FR, RRule.SA, RRule.SU],
  enumNames: Info.weekdays(), // default order is Monday - Sunday
  type: 'string',
},
```

I'm pretty sure doing this will remove the need for the `DAYS_OF_WEEK` object as well as the `getRRuleWeekDayConstants` helper. 

You'll also no longer need `Object.entries(DAYS_OF_WEEK)` in `getWeekDaysAndTimesFromRruleSet` because you can use `Info.weekdays()` directly.

https://moment.github.io/luxon/docs/class/src/info.js~Info.html#static-method-weekdays
https://react-jsonschema-form.readthedocs.io/en/latest/usage/single/#custom-labels-for-enum-fields

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaires/schemas/questionnaireSchema.js
> +          },
Refer to my comment above.

2020-07-08 19:34 UTC, UnsungHero97 commented on src/core/sagas/Sagas.js
> +    // fork(QuestionnairesSagas.createQuestionnaireWatcher),
Please remove.

2020-07-08 19:34 UTC, UnsungHero97 commented on src/core/redux/ReduxReducer.js
> +    // questionnaires: questionnairesReducer,
Any reason to keep this around?

2020-07-08 19:34 UTC, UnsungHero97 commented on src/containers/questionnaires/utils/index.js
> +      [COMPLETED_DATE_TIME_FQN.toString()]: [new Date()]
Shouldn't this be `new Date().toISOString()`?

2020-07-09 00:45 UTC, anzioka commented on src/core/redux/ReduxReducer.js
> +    // questionnaires: questionnairesReducer,
none. removed!

2020-07-09 00:52 UTC, anzioka commented on src/containers/questionnaires/utils/index.js
> +      [COMPLETED_DATE_TIME_FQN.toString()]: [new Date()]
I don't think it's necessary. The written value is a valid ISO date
<img width="1020" alt="Screen Shot 2020-07-08 at 5 51 43 PM" src="https://user-images.githubusercontent.com/15723547/86984540-b8770980-c143-11ea-8f8c-383deb65b2c1.png">

2020-07-09 01:03 UTC, anzioka commented on src/containers/questionnaires/components/DeleteQuestionnaireModal.js
> +export default React.memo<Props>(DeleteQuestionnaireModal);
Not necessary :)

2020-07-09 01:08 UTC, UnsungHero97 commented on src/containers/questionnaires/utils/index.js
> +      [COMPLETED_DATE_TIME_FQN.toString()]: [new Date()]
🤯

2020-07-09 01:10 UTC, UnsungHero97 commented on src/containers/questionnaires/utils/index.js
> +      [COMPLETED_DATE_TIME_FQN.toString()]: [new Date()]
Wait, I think you're looking at the wrong entity. The entity in the screenshot does not look like it's the `ol.partof` association entity because "Version" is not a property of `ol.partof`.

2020-07-09 01:23 UTC, anzioka commented on src/containers/questionnaires/constants/constants.js
> +};
Awesome :)

2020-07-09 01:39 UTC, anzioka commented on src/containers/questionnaires/constants/constants.js
> +};
Except that the property type in the schema should be an object otherwise validation test fails

2020-07-09 01:49 UTC, UnsungHero97 commented on src/containers/questionnaires/constants/constants.js
> +};
What do you mean?

2020-07-09 01:56 UTC, anzioka commented on src/containers/questionnaires/constants/constants.js
> +};
The enums are not strings. For example: RRule.MO
<img width="373" alt="Screen Shot 2020-07-08 at 6 51 34 PM" src="https://user-images.githubusercontent.com/15723547/86988001-20c9e900-c14c-11ea-9a8f-9637516bbac1.png">

In any case, when I used type 'string' I got a validation error.
<img width="1255" alt="Screen Shot 2020-07-08 at 6 53 29 PM" src="https://user-images.githubusercontent.com/15723547/86988128-65558480-c14c-11ea-8967-7b415f1473fc.png">

I think rjsf validates against the enum values, not enumNames

2020-07-09 02:00 UTC, anzioka commented on src/containers/questionnaires/utils/index.js
> +      [COMPLETED_DATE_TIME_FQN.toString()]: [new Date()]
It's actually the right entity. "Version" is part of the dst entity in the ol.partof association.

here is a larger screenshot
<img width="1142" alt="Screen Shot 2020-07-08 at 6 58 38 PM" src="https://user-images.githubusercontent.com/15723547/86988508-3ab7fb80-c14d-11ea-8cf3-2abd8f148f99.png">

2020-07-09 02:02 UTC, anzioka commented on src/containers/questionnaire/QuestionnaireSagas.js
> +        }
Makes sense!

2020-07-10 19:10 UTC, giuliacampana commented on src/containers/questionnaires/components/CreateQuestionnaireForm.js
> +  margin-bottom: 20px;
please alphabetize :)

2020-07-10 19:10 UTC, giuliacampana commented on src/containers/questionnaires/components/CreateQuestionnaireForm.js
> +  margin-top: 20px;
please alphabetize :)

2020-07-10 19:10 UTC, giuliacampana commented on src/containers/questionnaires/components/NewQuestionnaireConfirmation.js
> +  align-self: flex-start;
please alphabetize :)

2020-07-10 19:10 UTC, giuliacampana commented on src/containers/questionnaires/components/NewQuestionnaireConfirmation.js
> +        <Label>
do you think it's necessary to pass a default value to any of these lookups in `summary`?

2020-07-10 19:10 UTC, giuliacampana commented on src/containers/questionnaires/components/QuestionnaireDetailsModal.js
> +    margin-right: 10px;
please alphabetize :)

2020-07-10 19:10 UTC, giuliacampana commented on src/containers/questionnaires/components/QuestionnaireDetailsModal.js
> +  margin-bottom: 30px;
please alphabetize :)

2020-07-10 19:10 UTC, giuliacampana commented on src/containers/questionnaires/components/QuestionnaireDetailsModal.js
> +  questionnaireEKID :UUID;
please alphabetize :)

2020-07-10 19:10 UTC, giuliacampana commented on src/containers/questionnaires/components/QuestionnaireListItem.js
> +    color: ${NEUTRAL.N800};
please alphabetize :)

2020-07-10 19:10 UTC, giuliacampana commented on src/containers/questionnaires/components/QuestionnaireListItem.js
> +    text-overflow: ellipsis;
please alphabetize :)

2020-07-10 19:10 UTC, giuliacampana commented on src/containers/questionnaires/components/QuestionnaireListItem.js
> +  align-items: center;
please alphabetize :)

2020-07-10 19:10 UTC, giuliacampana commented on src/containers/questionnaires/components/QuestionnaireListItem.js
> +  padding: 20px 30px;
please alphabetize :)

2020-07-10 19:10 UTC, giuliacampana commented on src/containers/questionnaires/components/QuestionnairePreview.js
> +  margin: 5px 0 20px 0;
please alphabetize :)

2020-07-10 19:10 UTC, giuliacampana commented on src/core/sagas/Sagas.js
> +// import * as QuestionnairesSagas from '../../containers/questionnaires/QuestionnairesSagas';
looks like you can delete this comment.

2020-07-10 19:45 UTC, anzioka commented on src/containers/questionnaires/components/NewQuestionnaireConfirmation.js
> +        <Label>
No, it's not necessary. This component is rendered after paging through a bunch of required form inputs, from which the summary is computed. So the values rendered here are based on the form data which has already gone through  rjsf validation.

2020-07-10 19:48 UTC, anzioka commented on src/containers/questionnaire/QuestionnaireSagas.js
> +      deleteType: DeleteTypes.HARD
Following our conversation with @jokedurnez, we are going with HARD delete for now.

2020-07-14 17:15 UTC, solomontang approved these changes

2020-07-14 19:22 UTC, UnsungHero97 approved these changes

2020-07-14 19:24 UTC, merged