Feature/apps 1593 study participants table
methodic-labs/chronicle-web pull request #13
Opened 2020-01-08 00:02 UTC by anzioka

Add study participants
<img width="1070" alt="add_participant" src="https://user-images.githubusercontent.com/15723547/71939241-f0869b00-3166-11ea-972f-9421239a2c7e.png">

Change participant enrollment status
<img width="1129" alt="change_enrollment" src="https://user-images.githubusercontent.com/15723547/71939256-f7151280-3166-11ea-9592-a61adec10219.png">

Delete participant
<img width="1064" alt="delete_particant" src="https://user-images.githubusercontent.com/15723547/71939277-0300d480-3167-11ea-91d9-cc5108e793b7.png">

Show participant 
<img width="1025" alt="participant_info" src="https://user-images.githubusercontent.com/15723547/71939294-0c8a3c80-3167-11ea-9120-c0931e32ec4d.png">
info

participants table
<img width="1092" alt="participants_table" src="https://user-images.githubusercontent.com/15723547/71939307-14e27780-3167-11ea-92d9-de4f096b76cb.png">

2020-01-09 20:01 UTC, UnsungHero97 requested changes

2020-01-09 20:01 UTC, UnsungHero97 commented on src/core/edm/constants/DataModelConstants.js
> +};
Two things:

1. Please follow this enum pattern: 
https://github.com/openlattice/lattice-js/blob/develop/src/constants/types/ActionTypes.js

2. The server expects the status in all-caps, so `enrolled` and `not_enrolled` won't work. See here:
https://github.com/openlattice/chronicle-server/blob/develop/src/main/java/com/openlattice/chronicle/constants/ParticipationStatus.java

2020-01-09 20:01 UTC, UnsungHero97 commented on src/core/edm/constants/DataModelConstants.js
> +// @flow
The constants in this file are not data model constants. As such, I think the name of this file is misleading and it doesn't belong in `core/edm`.

2020-01-09 20:01 UTC, UnsungHero97 commented on src/utils/constants/UrlConstants.js
> +const STAGING :string = 'staging';
`LOCAL`, `PRODUCTION`, and `STAGING` are environment types, and I think they should follow the enum pattern, like `ENROLLMENT_STATUS`.

2020-01-09 20:01 UTC, UnsungHero97 commented on src/utils/api/AppApi.js
> +  }
Let's ignore webpack and get rid of `__ENV_DEV__` for this function. You can use this as a reference:

https://github.com/openlattice/lattice-auth/blob/develop/src/config/Configuration.js#L40

2020-01-09 22:01 UTC, anzioka commented on src/core/edm/constants/DataModelConstants.js
> +// @flow
Moved to utils/constants/GlobalConstants.js

2020-01-10 20:28 UTC, UnsungHero97 requested changes

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +function* changeEnrollmentWorker(action :SequenceAction) :Generator<*, *, *> {
Rename to `changeEnrollmentStatusWorker`.

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +function* changeEnrollmentWatcher() :Generator<*, *, *> {
Rename to `changeEnrollmentStatusWatcher`.

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +    const participatedInEntitySetId = yield select((state) => state.getIn(['edm', 'entitySetIds', PARTICIPATED_IN]));
This is totes fine. Just sharing a thought.

I prefer the following because it minimizes the `yield select`:

```
const { thing1, thing2 } = yield select((state) => ({
  thing1: state.getIn(...),
  thing2: state.getIn(...),
  ...
}));
```

This can also be refactored into a helper that returns many things from state, and then the destructuring will pick out what you care about.

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +}
It is not enough to just delete the participant from the entity set. You also need to delete all the relevant data that is collected for the participant. You need to rewrite this entirely and model it after `hardDeleteParticipantData` in the old app.

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +    }
You are calling `getParticipantsEnrollmentStatus.success()` only when `if (!participants.isEmpty())` is true. In the case that it's false, `.success()` is never invoked, which means the success reducer will not run.

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +    if (participants) {
What are your reasons for conditionally fetching participants? What use case requires this?

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +    const associationEntityData = processAssociationEntityData(fromJS(associations), entitySetIds, propertyTypeIds);
Just fyi, `processAssociationEntityData` will work for both `associations` and `fromJS(associations)`.

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/study/ParticipantsTable.js
> +          participantId={participants.getIn([participantEntityKeyId, PERSON_ID, 0])}
I recommend using the entity key id instead.

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/study/ParticipantsTable.js
> +          handleOnDeleteParticipant={() => handleOnDeleteParticipant()}
This can be just `handleOnDeleteParticipant={handleOnDeleteParticipant}`

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/study/ParticipantsTable.js
> +          handleOnChangeEnrollment={() => handleOnChangeEnrollment()}
This can be just `handleOnChangeEnrollment={handleOnChangeEnrollment}`.

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/study/components/ParticipantRow.js
> +    [, , iconColor] = PURPLES;
Why not `iconColor = PURPLES[2]`?

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/study/ParticipantsTable.js
> +    if (actionId === TOGGLE_ENROLLMENT) openEnrollmentModel();
Use either a switch or if-else.

2020-01-10 20:28 UTC, UnsungHero97 commented on src/containers/study/StudyParticipants.js
> +            onClick={() => openAddParticipantModal()}
```
onClick={openAddParticipantModal}
```

2020-01-10 20:28 UTC, UnsungHero97 commented on src/utils/constants/EnvTypes.js
> +  LOCAL:'local';
A space before `:`.

2020-01-10 20:28 UTC, UnsungHero97 commented on src/utils/constants/GlobalConstants.js
> +const STUDY_LOGIN_ROOT = 'https://openlattice.com/chronicle/login?studyId=';
A constant should be a constant. Here, you're providing an incomplete constant and requiring special knowledge about this constant. It's weird that an incomplete part of the query string is defined here, and the other *required* part of the query string must be added elsewhere.

What's another approach you can take?

2020-01-10 20:28 UTC, UnsungHero97 commented on src/utils/constants/ParticipantActionTypes.js
> +  TOGGLE_ENROLLMENT:'toggle_enrollment';
Spaces before `:`.

2020-01-10 20:36 UTC, anzioka commented on src/containers/studies/StudiesSagas.js
> +    const associationEntityData = processAssociationEntityData(fromJS(associations), entitySetIds, propertyTypeIds);
Ok, noted.

2020-01-10 22:07 UTC, anzioka commented on src/containers/study/components/ParticipantRow.js
> +    [, , iconColor] = PURPLES;
here's why:

<img width="650" alt="Screen Shot 2020-01-10 at 2 07 02 PM" src="https://user-images.githubusercontent.com/15723547/72189737-82361880-33b2-11ea-8c28-ea1a4f1ec1b3.png">

2020-01-10 22:25 UTC, anzioka commented on src/containers/study/ParticipantsTable.js
> +          participantId={participants.getIn([participantEntityKeyId, PERSON_ID, 0])}
Do you mean pass the entity key id as a prop to the ParticipantInfoModal component? I don't understand @UnsungHero97

2020-01-10 22:31 UTC, anzioka commented on src/containers/studies/StudiesSagas.js
> +    if (participants) {
For each particular study we only need to fetch participants once (when the participants tab is selected). Subsequent selections shouldn't result in a new fetch since the data is already in redux store.

2020-01-13 17:43 UTC, anzioka commented on src/utils/constants/GlobalConstants.js
> +const STUDY_LOGIN_ROOT = 'https://openlattice.com/chronicle/login?studyId=';
Ok, perhaps it makes more sense to provide functions that return the completed string?

2020-01-13 18:04 UTC, UnsungHero97 commented on src/containers/study/components/ParticipantRow.js
> +    [, , iconColor] = PURPLES;
I think we should ignore this warning for now. `[, , iconColor] = PURPLES;` is much less readable. Also, when the time comes to update LUK colors, it'll be much easier to replace/refactor `PURPLES[2]`.

2020-01-13 18:18 UTC, anzioka commented on src/containers/studies/StudiesSagas.js
> +    const participatedInEntitySetId = yield select((state) => state.getIn(['edm', 'entitySetIds', PARTICIPATED_IN]));
This looks much cleaner.

2020-01-13 18:42 UTC, UnsungHero97 commented on src/containers/study/ParticipantsTable.js
> +          participantId={participants.getIn([participantEntityKeyId, PERSON_ID, 0])}
Yes, that's what I mean. However, after looking at it again, I see that you're actually using `participantId` for the URL, so you can ignore my comment.

2020-01-13 22:00 UTC, anzioka commented on src/containers/study/components/ParticipantRow.js
> +    [, , iconColor] = PURPLES;
I agree, the destructuring is weird. Will ignore the warning.

2020-01-14 20:58 UTC, UnsungHero97 approved these changes

2020-01-14 20:59 UTC, merged