add custom form validation to require unique study participants
methodic-labs/chronicle-web pull request #16
Opened 2020-01-15 23:02 UTC by anzioka

<img width="1079" alt="validation" src="https://user-images.githubusercontent.com/15723547/72478943-f18f7c00-37a7-11ea-999e-aa01868ee8fc.png">

2020-01-15 23:05 UTC, UnsungHero97 requested changes

2020-01-15 23:05 UTC, UnsungHero97 commented on src/containers/study/components/AddParticipantForm.js
> +        validate={(formData, errors) => validateAddParticipantForm(formData, errors, participants, studyId)} />
I feel like there's some hook magic you can use here to avoid the inline function.

2020-01-15 23:08 UTC, anzioka commented on src/containers/study/components/AddParticipantForm.js
> +        validate={(formData, errors) => validateAddParticipantForm(formData, errors, participants, studyId)} />
yeah you are probably right. Looking into it!

2020-01-15 23:53 UTC, giuliacampana submitted a review, later dismissed

2020-01-15 23:53 UTC, giuliacampana commented on src/containers/study/components/AddParticipantForm.js
> +  };
Alternatively:
```
const validate = (formData, errors) => (
 validateAddParticipantForm(formData, errors, participants, studyId);
);

2020-01-15 23:53 UTC, giuliacampana commented on src/utils/FormUtils.js
> +  const eak = getEntityAddressKey(0, participantsEntitySetName, PERSON_ID);
change isn't necessary—this is nitpicky, but I think it's better to use more descriptive variable names if something isn't actually an acronym.

2020-01-15 23:58 UTC, anzioka commented on src/containers/study/components/AddParticipantForm.js
> +  };
Thanks! This looks cleaner.

2020-01-16 00:00 UTC, anzioka commented on src/utils/FormUtils.js
> +  const eak = getEntityAddressKey(0, participantsEntitySetName, PERSON_ID);
You are right!

2020-01-21 17:40 UTC, UnsungHero97 approved these changes

2020-01-21 17:40 UTC, merged