delete participant's data
methodic-labs/chronicle-web pull request #161
Opened 2020-07-02 22:38 UTC by anzioka

PR: delete participant's data. display spinner while deleting. Introduce timeout

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/15723547/86414695-8fed9c00-bc79-11ea-970b-11f423007114.gif)

deletion in progress
<img width="842" alt="pending" src="https://user-images.githubusercontent.com/15723547/86414793-df33cc80-bc79-11ea-81f9-1751a21ea0c2.png">

delete timeout
<img width="868" alt="timeout" src="https://user-images.githubusercontent.com/15723547/86414822-f4a8f680-bc79-11ea-9ef6-635180ccd60d.png">

2020-07-08 22:24 UTC, UnsungHero97 requested changes

2020-07-08 22:24 UTC, UnsungHero97 commented on src/containers/studies/StudiesReducer.js
> +            .setIn([DELETE_STUDY_PARTICIPANT, TIMEOUT], timeout)
There's no logic to reset `TIMEOUT`. Once it's set to `true`, it'll never be reset to `false`.

2020-07-09 12:30 UTC, anzioka commented on src/containers/studies/StudiesReducer.js
> +            .setIn([DELETE_STUDY_PARTICIPANT, TIMEOUT], timeout)
Added reset on closing delete modal

2020-07-13 22:00 UTC, UnsungHero97 approved these changes

2020-07-13 22:01 UTC, merged