add search filter in the participants page
methodic-labs/chronicle-web pull request #17
Opened 2020-01-16 22:37 UTC by anzioka

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15723547/72568675-86a87880-386d-11ea-8da6-4a899edee1c5.gif)

<img width="1120" alt="search" src="https://user-images.githubusercontent.com/15723547/72568716-9b850c00-386d-11ea-8955-c216e775bd0d.png">

2020-01-16 22:43 UTC, anzioka commented
<img width="1094" alt="Screen Shot 2020-01-16 at 2 43 13 PM" src="https://user-images.githubusercontent.com/15723547/72569143-907eab80-386e-11ea-8278-6a81ec4e711d.png">

2020-01-16 23:59 UTC, UnsungHero97 requested changes

2020-01-16 23:59 UTC, UnsungHero97 commented on src/containers/study/StudyParticipants.js
> +      .valueSeq()
I don't think you need to do `.valueSeq()`.

2020-01-16 23:59 UTC, UnsungHero97 commented on src/containers/study/StudyParticipants.js
> +  }, [participants]);
Would this work?

```
const participants :Map = useSelector(...);
const [filteredParticipants, setFilteredParticipants] = useState(participants);
```

2020-01-17 00:15 UTC, anzioka commented on src/containers/study/StudyParticipants.js
> +      .valueSeq()
You are right.

2020-01-17 01:43 UTC, anzioka commented on src/containers/study/StudyParticipants.js
> +  }, [participants]);
I tried that but it fails the first time the page is rendered (when `getStudyParticipants` is dispatched to fetch data). I think the reason is that `participants` is initially empty and therefore `filteredParticipants` is initialized as an empty map. After the data is fetched, `filteredParticipants` is not updated, thus the table is not rendered.

2020-01-21 17:42 UTC, UnsungHero97 approved these changes

2020-01-21 17:42 UTC, merged