Enable researchers to choose whether to download raw/preprocessed data
methodic-labs/chronicle-web pull request #20
Opened 2020-01-31 19:37 UTC by anzioka

<img width="1016" alt="download" src="https://user-images.githubusercontent.com/15723547/73568756-eb430600-441d-11ea-8c7d-05865fa4a804.png">

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15723547/73568823-03b32080-441e-11ea-8c4f-220cd7725a84.gif)

2020-02-07 22:18 UTC, UnsungHero97 requested changes

2020-02-07 22:18 UTC, UnsungHero97 commented on package.json
> +    "lattice-ui-kit": "0.23.0",
LUK is at `v0.25.0` now. Also, can you bump `lattice-auth` to `v0.18.0`?

2020-02-07 22:18 UTC, UnsungHero97 commented on src/containers/study/components/DownloadParticipantDataModal.js
> +  };
Instead of downloading both at the same time, how do you feel about having dedicated download buttons per type?

2020-02-07 23:40 UTC, anzioka commented
<img width="1117" alt="data download" src="https://user-images.githubusercontent.com/15723547/74073697-1c907880-49c0-11ea-9ff6-39dd37eacd20.png">

2020-02-07 23:59 UTC, UnsungHero97 requested changes

2020-02-07 23:59 UTC, UnsungHero97 commented on src/containers/study/components/DownloadParticipantDataModal.js
> +  participantEntityKeyId:?UUID;
This doesn't need to be `:?`, right?

2020-02-08 00:08 UTC, UnsungHero97 submitted a review, later dismissed

2020-02-08 00:10 UTC, UnsungHero97 approved these changes

2020-02-08 00:11 UTC, merged