Task/create tud interface
methodic-labs/chronicle-web pull request #218
Opened 2020-07-30 05:09 UTC by anzioka

PR:

milestone 0 of the time use diary: 

1) interface to select activities during a full day duration and specify time spans for each activity
2) basic summary page showing each activity and time span, and ability to switch to a specific page in the PageMachine context and make changes.

<img width="439" alt="Screen Shot 2020-07-29 at 9 58 48 PM" src="https://user-images.githubusercontent.com/15723547/88883025-17cab580-d1e8-11ea-8743-67ab8a792851.png">
<img width="447" alt="Screen Shot 2020-07-29 at 9 59 19 PM" src="https://user-images.githubusercontent.com/15723547/88883029-1a2d0f80-d1e8-11ea-9c2e-b62b552e773a.png">
<img width="433" alt="Screen Shot 2020-07-29 at 9 58 30 PM" src="https://user-images.githubusercontent.com/15723547/88883034-1c8f6980-d1e8-11ea-83fe-14573753ea79.png">

2020-08-10 23:38 UTC, UnsungHero97 requested changes

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/components/QuestionnaireForm.js
> +          render={(pagedProps) => {
Is there a reason why the body for the `render` prop is not its own component?

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/components/QuestionnaireForm.js
> +            }
A few thoughts...

First, if you use `if-else` blocks, you can avoid overwriting the schema variables on every render:

```
let dataSchema;
let uiSchema;

if (page === 0) {
  dataSchema = PreSurveySchema.schema;
  uiSchema = PreSurveySchema.uiSchema;
}
else if (page === 1) {
  dataSchema = DaySpanSchema.schema;
  uiSchema = DaySpanSchema.uiSchema;
}
else {
  dataSchema = createFormSchema(page, pagedData);
  uiSchema = createUiSchema(page);
}
```

Second, these assignments are dangerous. I believe any mutations on the left will also apply to the right. The way I've approached this in the past is to "clone" the schemas like so:

```
const dataSchema = JSON.parse(JSON.stringify(Schemas.dataSchema));
const uiSchema = JSON.parse(JSON.stringify(Schemas.uiSchema));
```

There are probably better ways to do the "clone"... let me know if you think of other ways.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/components/QuestionnaireForm.js
> +                  </Button>
I know we're not submitting data right now, but in the future, these buttons must be disabled during the submit request, i.e. `SUBMIT_RS === RequestStates.PENDING`.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/components/QuestionnaireForm.js
> +                const endTimeInput = document.getElementById(`root_${getPageSectionKey(page, 0)}_endTime`);
Whoa... why do you need to do this?

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/components/TimeUseSummary.js
> +`;
How many components do you have in this project that are similar to this?

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/components/TimeUseSummary.js
> +`;
How many components do you have in this project that are similar to this?

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/components/TimeUseSummary.js
> +  padding: 0;
If you're going to nuke the margin and padding, might as well just use a `div` and avoid the extra css.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/components/TimeUseSummary.js
> +                startIcon={<FontAwesomeIcon icon={faPencilAlt} />}>
I recommend moving the icon into a constant outside of the component.

```
const EditIcon = (
  <FontAwesomeIcon icon={faPencilAlt} />
);
```

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/constants/ActivitiesConstants.js
> +const MEDIA = 'Media Use (Tv, Books, Apps, etc)';
`Tv` should be `TV`?

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/constants/ActivitiesConstants.js
> +  { name: OTHER, description: '', followup: false }
What is the `description` used for?

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/PreSurveySchema.js
> +          A non-typical day would include a school closing, being on vacation, or being home sick.`,
For multi-line strings like this, I recommend defining these as constants like so:

```
const TYPICAL_DAY_TITLE = 'An important part of this project is to find out how children spend their time'
  + ' during the week. Was yesterday a typical weekday for you and your child?'
  + ' A non-typical day would include a school closing, being on vacation, or being home sick.';
```

This way, you don't have to worry about new-line characters from the templated string and how the browser is going to render them. Additionally, it avoids submitting new-line characters, though I'm not entirely sure if that's the case to begin with.

If you really need the specific new-line cutoffs, I still recommend using a constant.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/EatingIndoorRecSchema.js
> +      on in the background while your child was doing this activity?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/EatingIndoorRecSchema.js
> +                phone at any point while your child did this activity?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/EatingIndoorRecSchema.js
> +                phone at any point while your child did this activity?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/EatingIndoorRecSchema.js
> +            books, magazines, radio or CDs, cell phone/smart phone, laptop or a tablet?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/EatingIndoorRecSchema.js
> +                  phone at any point while your child did this activity?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/EatingIndoorRecSchema.js
> +                        for younger children, or for adults?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/MediaUseSchema.js
> +      radio or CDs, cell phone/smart phone, laptop or a tablet? `,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/MediaUseSchema.js
> +        at any point while your child did this activity?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/MediaUseSchema.js
> +               enter 50; if you used your device the entire time, enter 100.`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/MediaUseSchema.js
> +                  for older children, for younger children, or for adults?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/MediaUseSchema.js
> +                 or leave blank`
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/OutdoorRecSchema.js
> +            books, magazines, radio or CDs, cell phone/smart phone, laptop or a tablet?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/OutdoorRecSchema.js
> +                on in the background while your child was doing this activity?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/OutdoorRecSchema.js
> +                  phone at any point while your child did this activity?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/OutdoorRecSchema.js
> +                  phone at any point while your child did this activity?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/OutdoorsSchema.js
> +        at any point while your child did this activity?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/OutdoorsSchema.js
> +                  'Social call', 'Entertainment', 'Social media']
Formatting. Either all on one line, or each on its own line.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/OutdoorsSchema.js
> +            books, magazines, radio or CDs, cell phone/smart phone, laptop or a tablet?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/OutdoorsSchema.js
> +                  older children, younger children, or adults?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/OutdoorsSchema.js
> +                on in the background while your child was doing this activity?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/SleepingSchema.js
> +       enter 10; if on the full time, enter 100.`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/SleepingSchema.js
> +          but does not include white noise machines. `,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/SleepingSchema.js
> +                        on in the background while your child was doing this activity?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/SleepingSchema.js
> +                        for younger children, or for adults?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/SleepingSchema.js
> +                        on in the background while your child was doing this activity?`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/schemas/followup/SleepingSchema.js
> +                                 enter 10; if on the full time, enter 100.`,
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/utils/index.js
> +  const prevEndTime = pageNum === 2
`2` is an important value and should be defined as a constant somewhere.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/utils/index.js
> +                finished ${(prevActivity || {}).description}?`),
Same comment about multi-line strings.

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/utils/index.js
> +              : 'When did the selected activity end?'
Formatting. `?` and `:` should be on their own lines.

```
title: currentActivity
  ? `When...`
  : 'When...'
```

2020-08-10 23:38 UTC, UnsungHero97 commented on src/containers/tud/utils/index.js
> +        classNames: (pageNum === 1 ? 'hidden' : 'column-span-12')
`1` is an important value and should be defined as a constant somewhere.

2020-08-12 18:39 UTC, anzioka commented on src/containers/tud/components/QuestionnaireForm.js
> +            }
Can you expound on your second point? i.e what do you mean by mutations on the left will also apply to the right?

2020-08-12 18:39 UTC, anzioka commented on src/containers/tud/components/QuestionnaireForm.js
> +                  </Button>
Noted.

2020-08-12 19:03 UTC, anzioka commented on src/containers/tud/components/QuestionnaireForm.js
> +                const endTimeInput = document.getElementById(`root_${getPageSectionKey(page, 0)}_endTime`);
After selecting a primary activity, the label on the next question needs to be updated to reference the selected activity. For example, after selecting `Sleeping/Resting` the next question would be `When did your child stop sleeping/resting?`

2020-08-12 19:12 UTC, anzioka commented on src/containers/tud/constants/ActivitiesConstants.js
> +  { name: OTHER, description: '', followup: false }
Usage:

`When did your child stop ${activity.description}?`

2020-08-12 19:34 UTC, solomontang submitted a review, later dismissed

2020-08-12 19:34 UTC, solomontang commented on src/containers/tud/utils/index.js
> +    }
There is a way to have the date/time picker also set min/max ranges. we should investigate this with fabricate moving forward.

2020-08-12 19:34 UTC, solomontang commented on src/containers/tud/schemas/followup/OutdoorsSchema.js
> +              [MEDIA_AGE]: { // TODO: otherText radio
Is this TODO still relevant

2020-08-12 19:35 UTC, solomontang commented
damn that's soo much padding..

2020-08-12 19:41 UTC, solomontang commented on src/containers/tud/components/QuestionnaireForm.js
> +            }
He's suggesting a defensive copy of the schema if for some reason any mutations to dataSchema causes PreSurveySchema to change. Could always make schemas immutable.

2020-08-12 20:00 UTC, anzioka commented on src/containers/tud/components/QuestionnaireForm.js
> +            }
Ok, makes sense! 

in that case, I think I could use lodash cloneDeep (https://lodash.com/docs/4.17.15#cloneDeep) to make a deep clone

2020-08-13 17:52 UTC, solomontang approved these changes

2020-08-13 17:52 UTC, solomontang commented on src/containers/tud/components/QuestionnaireForm.js
> +  }
I see you've gone the route of making a deep copy. I wonder if you could have gotten away with Object.freeze when declaring the schemas.

2020-08-13 17:52 UTC, solomontang commented on src/containers/tud/components/QuestionnaireForm.js
> +    //
rogue comment

2020-08-13 17:55 UTC, anzioka commented on src/containers/tud/components/QuestionnaireForm.js
> +  }
ah yes, I think that would have worked too.

2020-08-18 22:31 UTC, UnsungHero97 approved these changes

2020-08-18 22:31 UTC, merged