Feature/apps 1739 create chronicle survey
methodic-labs/chronicle-web pull request #24
Opened 2020-02-15 01:09 UTC by anzioka

Display apps used by participants filtered by the current date
<img width="1443" alt="survey" src="https://user-images.githubusercontent.com/15723547/74578974-870b6080-4f4c-11ea-9f48-4891df646020.png">

**Successful submission:**
<img width="811" alt="successful" src="https://user-images.githubusercontent.com/15723547/74578985-92f72280-4f4c-11ea-81d6-0b42ee3dce47.png">

**Submission failure:**
<img width="1023" alt="error_state" src="https://user-images.githubusercontent.com/15723547/74578996-9c808a80-4f4c-11ea-83f8-d9fdf96ba84e.png">

**Mobile View:**
<img width="448" alt="mobile" src="https://user-images.githubusercontent.com/15723547/74579015-b5893b80-4f4c-11ea-8a11-41b9f2567507.png">

2020-02-25 19:53 UTC, UnsungHero97 requested changes

2020-02-25 19:53 UTC, UnsungHero97 commented on package.json
> +    "axios": "~0.19.2",
Please keep patch version values at 0.

2020-02-25 19:53 UTC, UnsungHero97 commented on package.json
> +    "qs": "~6.9.1",
Please keep patch version values at 0.

2020-02-25 19:53 UTC, UnsungHero97 commented on src/utils/constants/AppUserTypes.js
> +type AppUserType = $Values<AppUserTypeEnum>;
I found a slightly better way to do this:

```
const AppUserTypes :{|...AppUserTypeEnum|} = Object.freeze({
 ...
});
type AppUserType = $Values<typeof AppUserTypes>;
```

2020-02-25 19:53 UTC, UnsungHero97 commented on src/utils/api/AppApi.js
> +import ParticipantDataTypes from '../constants/ParticipantDataTypes';
Please run the import sorter.

2020-02-25 19:53 UTC, UnsungHero97 commented on src/index.js
> +import SurveyContainer from './containers/survey/SurveyContainer';
Please run the import sorter.

2020-02-25 19:53 UTC, UnsungHero97 commented on src/containers/survey/SurveyContainer.js
> +  const queryParams = qs.parse(history.location.search, { ignoreQueryPrefix: true });
Question: are the params before or after the hash `#`?

If before, I don't see a reason to use `history` from `react-router`; just use `window.location.search`. If after, you should use `location` instead of `history` via `useLocation()`.

2020-02-25 19:53 UTC, UnsungHero97 commented on src/containers/survey/SurveyContainer.js
> +  );
This doesn't need to be inside `SurveyContainer`. It can safely be defined outside, it's basically a constant.

2020-02-25 19:53 UTC, UnsungHero97 commented on src/containers/survey/SurveyContainer.js
> +                          {getCurrentDate()}
This doesn't need to be a function.

2020-02-25 19:53 UTC, UnsungHero97 commented on src/containers/survey/SurveyContainer.js
> +  const getCurrentDate = () => getFullDateFromIsoDate(new Date().toISOString());
It looks like `getFullDateFromIsoDate` is only used here and only used with a new date. Based on that, `getFullDateFromIsoDate` doesn't need to exist because you can accomplish the same thing like this:

```
const fullDate :string = DateTime.local().toLocaleString(DateTime.DATE_FULL); // 'February 25, 2020'
```

2020-02-25 19:53 UTC, UnsungHero97 commented on src/containers/survey/SurveyReducer.js
> +const INITIAL_STATE :Map<*, *, *> = fromJS({
The flow annotation is wrong `:Map<*, *, *>`. Maps only have a key and a value. Separately, since we're not yet using immutable's flow definitions, drop the `*` and just use `:Map`.

2020-02-25 19:53 UTC, UnsungHero97 commented on src/containers/survey/SurveyTable.js
> +  };
See @solomontang's comment on this: https://github.com/Lattice-Works/pretrial-case-management/pull/728#discussion_r383566077

2020-02-25 19:53 UTC, UnsungHero97 commented on src/containers/survey/SurveyTable.js
> +                { renderErrorModal() }
I don't see a reason to have `SubmissionFailureModal` inside the function. Why not just place it here directly?

2020-02-25 19:53 UTC, UnsungHero97 commented on src/containers/survey/components/TableRow.js
> +    <>
`RowWrapper` wraps everything, so you don't need the fragments.

2020-02-25 20:07 UTC, UnsungHero97 requested changes

2020-02-25 20:07 UTC, UnsungHero97 commented on src/containers/survey/SurveySagas.js
> +    if (url === null) throw new Error('Invalid Url');
`if (!url)` covers `null` and other falsy values.

2020-02-25 20:07 UTC, UnsungHero97 commented on src/containers/survey/SurveySagas.js
> +      .map((entity) => entity.delete(OPENLATTICE_ID_FQN));
You can avoid this reassignment by moving the `entity.delete` into the `forEach` above.

2020-02-25 20:07 UTC, UnsungHero97 commented on src/containers/survey/SurveySagas.js
> +    });
This block of code belongs in something like `ChronicleApi`, similar to `lattice-js`. Please refactor:

```
const response = yield call(ChronicleApi.updateAppsUsageAssociationData, data);
```

2020-02-25 20:07 UTC, UnsungHero97 commented on src/containers/survey/SurveySagas.js
> +    });
This block of code belongs in something like `ChronicleApi`, similar to `lattice-js`. Please refactor:

```
const response = yield call(ChronicleApi.getParticipantAppsUsageData);
```

2020-02-26 22:07 UTC, anzioka commented
after replacing useState with useReducer: 
![survey](https://user-images.githubusercontent.com/15723547/75392557-227fc800-58a1-11ea-9bff-3836d31b1006.gif)

2020-03-06 22:04 UTC, UnsungHero97 approved these changes

2020-03-16 21:24 UTC, merged