Task/apps 2210/app configs
methodic-labs/chronicle-web pull request #250
Opened 2020-08-22 06:56 UTC by anzioka

App configs -> handle switching organization

2020-09-16 21:58 UTC, bergieboy requested changes

2020-09-16 21:58 UTC, bergieboy commented on src/containers/app/AppReducer.js
> +        FAILURE: () => state.setIn([GET_CONFIGS, REQUEST_STATE], RequestStates.PENDING),
I think this should be `RequestStates.FAILURE`

2020-09-16 21:58 UTC, bergieboy commented on src/containers/app/AppReducer.js
> +        FAILURE: () => state.setIn([GET_CONFIGS, REQUEST_STATE], RequestStates.PENDING),
Also, I don't see a failure request sequence in `getConfigsWorker`

2020-09-16 21:58 UTC, bergieboy commented on src/containers/app/AppSagas.js
> +    workerResponse.error = error;
should we include `yield put(getConfigs.failure(action.id, error));` here since you have a failure case in your reducer?

2020-09-16 21:58 UTC, bergieboy commented on src/containers/study/StudyDetailsContainer.js
> +import { STUDIES_REDUX_CONSTANTS, APP_REDUX_CONSTANTS } from '../../utils/constants/ReduxConstants';
sort imports

2020-09-16 21:58 UTC, bergieboy commented on src/core/edm/EDMUtils.js
> +const { SELECTED_ORG_ID, ENTITY_SET_IDS_BY_ORG_ID } = APP_REDUX_CONSTANTS;
sort imports

2020-09-16 21:58 UTC, bergieboy commented on src/core/sagas/Sagas.js
> +    fork(AppSagas.switchOrganizationWatcher),
sort

2020-09-16 22:05 UTC, anzioka commented on src/containers/app/AppSagas.js
> +    workerResponse.error = error;
Correct.

2020-09-16 22:06 UTC, anzioka commented on src/containers/app/AppReducer.js
> +        FAILURE: () => state.setIn([GET_CONFIGS, REQUEST_STATE], RequestStates.PENDING),
Good catch. Updating.

2020-09-16 22:11 UTC, anzioka commented on src/core/edm/EDMUtils.js
> +const { SELECTED_ORG_ID, ENTITY_SET_IDS_BY_ORG_ID } = APP_REDUX_CONSTANTS;
These are correctly sorted.

2020-09-16 22:45 UTC, bergieboy submitted a review, later dismissed

2020-09-16 23:05 UTC, solomontang commented on src/containers/app/AppContainer.js
> +  // console.log(organizations, selectedOrgId);
remove

2020-09-16 23:05 UTC, solomontang submitted a review, later dismissed

2020-10-01 04:37 UTC, UnsungHero97 requested changes

2020-10-01 04:37 UTC, UnsungHero97 commented on src/containers/app/AppSagas.js
> +function* getConfigsWorker(action :SequenceAction) :Saga<*> {
No change required, just a note: `lattice-sagas` exports a `WorkerResponse` type that you can use.

```
import type { WorkerResponse } from 'lattice-sagas';

function* getConfigsWorker(action :SequenceAction) :Saga<WorkerResponse> {
  let workerResponse :WorkerResponse;
  try {
    ...
    workerResponse = { data };
  }
  catch (error) {
    workerResponse = { error };
    ...
  }
  finally { ... }
  return workerResponse;
}
```

2020-10-01 04:37 UTC, UnsungHero97 commented on src/containers/app/AppSagas.js
> +    }
I think this will always be false.

2020-10-01 04:37 UTC, UnsungHero97 commented on src/containers/app/AppSagas.js
> +      }), {})
You're not checking for `response.error` so I believe this will throw if one of the requests fails.

2020-10-01 04:37 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireContainer.js
> +  }, [dispatch, questionnaireId, studyId, organizationId]);
No change required, just an observation. Do you really need to pass `organizationId` around? The selected organization id is available in the redux store, so you can just `yield select(selectOrganizationId())` in the sagas.

2020-10-01 04:37 UTC, UnsungHero97 commented on src/containers/app/AppReducer.js
> +          }
Why `Object.keys().includes` instead of just `organizations[storedOrgId]`?

2020-10-01 04:37 UTC, UnsungHero97 commented on src/containers/app/AppReducer.js
> +  [APP_MODULES_ORG_LIST_MAP]: Map(),
Not gonna lie... reading `APP_MODULES_ORG_LIST_MAP` makes my brain hurt.

2020-10-01 04:37 UTC, UnsungHero97 commented on src/core/edm/EDMUtils.js
> +  let result = Map().asMutable();
No change required, just a note. Docs recommend using `withMutations()` over `asMutable`:

> If possible, use withMutations to work with temporary mutable copies as it provides an easier to use API and considers many common optimizations.

https://immutable-js.github.io/immutable-js/docs/#/Map/asMutable

2020-10-01 04:37 UTC, UnsungHero97 commented on src/containers/studies/StudiesActions.js
> +const getNotificationsEntity = newRequestSequence(GET_NOTIFICATIONS_ENTITY);
Please change `ENTITY` to `EKID` because this is actually for getting the entity key id, not the entity data itself.

2020-10-01 04:37 UTC, UnsungHero97 commented on src/containers/studies/StudiesReducer.js
> +  [NOTIFICATIONS_EKID]: 0,
Why `0`? This feels like a special value.

2020-10-01 04:37 UTC, UnsungHero97 commented on src/core/edm/EDMUtils.js
> +const selectPropertyTypeIds = () => (state :Map) => state.getIn(['edm', 'propertyTypeIds']);
A great candidate for `lattice-utils`, though more work will be needed.

2020-10-01 04:37 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +        [PART_OF, notificationsEKID || 0, NOTIFICATION, studyEntityKeyId, STUDIES, {
I recommend moving `notificationsEKID || 0` into its own variable. Or, you can basically do this same thing but in the selector above.

2020-10-01 04:37 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +      (state) => state.getIn(['studies', PART_OF_ASSOCIATION_EKID_MAP, studyId])
Why go from `STUDIES` to `'studies'` here when you use `STUDIES` in other places?

2020-10-01 04:37 UTC, UnsungHero97 commented on src/containers/study/ParticipantsTable.js
> +  const selectedOrgId :UUID = useSelector((state) => state.getIn(['app', SELECTED_ORG_ID]));
Might as well make this a helper selector like with others you've done.

2020-10-01 04:37 UTC, UnsungHero97 commented on src/containers/study/StudyDetailsContainer.js
> +  const studyId :UUID = getIdFromMatch(match) || '';
No change required. `lattice-utils` exports `getParamFromMatch`. Here's how to use it:

```
const matchOrg = useRouteMatch(Routes.ORG);
const orgId :?UUID = getParamFromMatch(matchOrg, Routes.ORG_ID_PARAM);
```

2020-10-01 04:37 UTC, UnsungHero97 commented on src/utils/constants/ReduxConstants.js
> +  APP_MODULES_ORG_LIST_MAP: 'appModulesOrgListMap',
🤯

2020-10-01 04:37 UTC, UnsungHero97 commented on src/utils/AppUtils.js
> +  const csrfToken = AuthUtils.getCSRFToken() ?? '';
Whoa, what's `??`?

2020-10-01 04:37 UTC, UnsungHero97 commented on src/utils/AppUtils.js
> +  const csrfToken = AuthUtils.getCSRFToken() ?? '';
OHHH!!! 🤯 🤯 🤯 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

2020-10-01 04:37 UTC, UnsungHero97 commented on src/utils/AppUtils.js
> +const processAppConfigs = (appConfigsByModule :Object) => {
This feels like magic.

2020-10-01 11:58 UTC, anzioka commented on src/containers/app/AppSagas.js
> +    }
Agreed, but only if we assume that the core module is guaranteed to exist on prod. I don't think we have to make that assumption though, so we should keep this check in place.

2020-10-01 12:27 UTC, anzioka commented on src/containers/questionnaire/QuestionnaireContainer.js
> +  }, [dispatch, questionnaireId, studyId, organizationId]);
The `organizationId` is parsed from the url, and is not the id of the selected organization, thus needs to be passed around. This component is rendered when a participant needs to fill out survey, hence the concept of 'selecting an organization' does not exist.

2020-10-01 12:32 UTC, anzioka commented on src/containers/app/AppReducer.js
> +  [APP_MODULES_ORG_LIST_MAP]: Map(),
aptly named:
```
{
  chronicle: [org1, org2, org3],
  data_collection: [org1, org4]
}
```

2020-10-01 12:39 UTC, anzioka commented on src/core/edm/EDMUtils.js
> +  let result = Map().asMutable();
updated

2020-10-01 12:58 UTC, anzioka commented on src/containers/studies/StudiesReducer.js
> +  [NOTIFICATIONS_EKID]: 0,
No idea why I set this to be `0`. In any case, there is no good reason not to initialize as `undefined`

2020-10-01 13:09 UTC, anzioka commented on src/containers/studies/StudiesSagas.js
> +      (state) => state.getIn(['studies', PART_OF_ASSOCIATION_EKID_MAP, studyId])
I refactored to use STUDIES to refer to a collection template type name. To avoid confusion, I have changed studies -> STUDIES_REDUX_CONSTANTS.STUDIES

2020-10-01 16:23 UTC, UnsungHero97 commented on src/containers/app/AppSagas.js
> +    }
That's not what I'm referring to. It is guaranteed that the `appModulesRes` object will ALWAYS have the all the keys, so the `.includes` will always be true, totally unrelated to the actual request.

2020-10-01 17:20 UTC, UnsungHero97 approved these changes

2020-10-01 17:52 UTC, bergieboy approved these changes

2020-10-01 19:21 UTC, merged