Update UI of time use diary to match new flowchart
methodic-labs/chronicle-web pull request #289
Opened 2020-09-25 20:32 UTC by anzioka

<img width="376" alt="Screen Shot 2020-09-25 at 1 30 46 PM" src="https://user-images.githubusercontent.com/15723547/94313384-7932aa80-ff33-11ea-8b7e-f305a45f70ea.png">

<img width="372" alt="Screen Shot 2020-09-25 at 1 29 27 PM" src="https://user-images.githubusercontent.com/15723547/94313260-3ffa3a80-ff33-11ea-926f-f046029ad1df.png">

<img width="425" alt="Screen Shot 2020-09-25 at 1 29 14 PM" src="https://user-images.githubusercontent.com/15723547/94313241-396bc300-ff33-11ea-8d1b-1fe238b7dcdc.png">

2020-09-25 20:52 UTC, solomontang requested changes

2020-09-25 20:52 UTC, solomontang commented on src/containers/tud/constants/SchemaFieldsTitles.js
> +  [SLEEP_ARRANGEMENT]: 'Las night, what was your child\'s sleeping arrangement?',
Typo. "Last night,..."

2020-09-26 02:33 UTC, solomontang approved these changes

2020-09-28 21:57 UTC, UnsungHero97 approved these changes

2020-09-29 18:16 UTC, merged