Feature/apps 1588 create studies page
methodic-labs/chronicle-web pull request #3
Opened 2019-12-05 18:01 UTC by anzioka

Created page to display list of studies. At the top of the page there is a 'Create Study' button will show modal with form to create a new page (not yet implemented) Each study is rendered in a LUK card and contains basic info about the study. The number label at the top right of the page is a placeholder for the number of participants and will be replaced by the actual number.  On clicking each card details about the study are displayed (haven't yet implemented this). 

<img width="1075" alt="study_page" src="https://user-images.githubusercontent.com/15723547/70260713-b714d700-1745-11ea-9a4a-a40fd23f1037.png">

2019-12-05 18:34 UTC, UnsungHero97 requested changes
Please run `npm run lint` and `npm run flow` and fix any errors.

2019-12-05 19:36 UTC, giuliacampana commented on src/utils/constants/DataModelConstants.js
> +};
Looks good! One thing to note is that we usually store property types (and entity types) as `FullyQualifiedNames`. So, for example: 

```
import { Models } from 'lattice';

const { FullyQualifiedName } = Models;

export const PROPERTY_TYPES = {
  PERSON_ID: new FullyQualifiedName('nc.SubjectIdentification'),
  PARTICIPANT_ID: new FullyQualifiedName('justice.xref'),
  ...
```

This is what I'm referring to: https://github.com/openlattice/lattice-js/blob/develop/src/models/FullyQualifiedName.js.

2019-12-05 19:48 UTC, UnsungHero97 requested changes

2019-12-05 19:48 UTC, UnsungHero97 commented on src/utils/constants/DataModelConstants.js
> +export const ENTITY_SETS = {
This belongs in `core/edm/constants/EntitySetNames.js`.

2019-12-05 19:48 UTC, UnsungHero97 commented on src/utils/constants/DataModelConstants.js
> +export const PROPERTY_TYPES = {
This belongs in `core/edm/constants/FullyQualifiedNames.js`.

2019-12-05 19:48 UTC, UnsungHero97 commented on src/utils/constants/DataModelConstants.js
> +export const GENERAL_STRING_ID_PT_ID = 'ee3a7573-aa70-4afb-814d-3fad27cda988';
What is this id?

2019-12-05 19:53 UTC, giuliacampana commented on src/components/StudyCard.js
> +      <Card onClick={(event) => handleCardClick(event)} data-study-id={study.id}>
Not sure if the linter should have caught this, but typically, for prop names, we use `camelCase` as opposed to `kebab-case` (is that what it's called?), as you have with the `onClick` prop:
```
dataStudyId={study.Id}

2019-12-05 19:56 UTC, giuliacampana commented on src/containers/studies/StudiesContainer.js
> +                ))}
Also wondering if the linter should have caught this... but the brackets should each be on their own line! Also might be a good idea in this case, with 3 props, to put them each on their own line:
```
<CardGrid>
  {
    formatedStudies.map((study) => (
      <StudyCard
          key={study.id}
          study={study}
          handleCardClick={this.handleCardClick} />
    ))
  }
</CardGrid>

2019-12-05 20:13 UTC, giuliacampana commented on src/containers/studies/StudiesSagas.js
> +    );
I'm just curious why the `searchEntitySetData` endpoint is used here, as opposed to simply using `DataApi.getEntitySetData`. I see it's used in the original `StudiesSagas` too — @UnsungHero97 I assume this endpoint was used to limit the number of results—but if there were 1000 studies, that still seems like a pretty large number of results to display... unless the intention was to paginate if over a certain threshold were returned? In that case, then I think it would make more sense to use the `executeSearch` endpoint, since now it's easy to get paginated results from the backend, ya?

2019-12-05 20:17 UTC, anzioka commented on src/utils/constants/DataModelConstants.js
> +export const GENERAL_STRING_ID_PT_ID = 'ee3a7573-aa70-4afb-814d-3fad27cda988';
ported over the constants file from the old project without making any changes ... but I have removed the Id since there doesn't seem to be any use for it

2019-12-05 21:04 UTC, UnsungHero97 commented on src/components/StudyCard.js
> +      <Card onClick={(event) => handleCardClick(event)} data-study-id={study.id}>
@giuliacampana this is actually correct. `data-` attributes are special:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset

2019-12-05 21:42 UTC, UnsungHero97 requested changes

2019-12-05 21:42 UTC, UnsungHero97 commented on package.json
> +    "prop-types": "^15.7.2",
We use Flow instead of `prop-types`. Please remove.

https://flow.org/

2019-12-05 21:42 UTC, UnsungHero97 commented on package.json
> +    "lint:js": "eslint --config .eslintrc --fix src",
I don't think autofixing is a good idea. Please remove.

2019-12-05 21:42 UTC, UnsungHero97 commented on src/components/StudyCard.js
> +  font-size: 14px;
Please sort in alphabetical order.

2019-12-05 21:42 UTC, UnsungHero97 commented on src/components/StudyCard.js
> +type Props = {
I'm pretty sure Flow will complain about this. You'll want to do the following:

```
type Props = {
  handleOnClickCard :() => void; // you can also do :Function
  study :Object;
};
```

2019-12-05 21:42 UTC, UnsungHero97 commented on src/components/StudyCard.js
> +      <Card onClick={(event) => handleCardClick(event)} data-study-id={study.id}>
`onClick={handleCardClick}`

2019-12-05 21:42 UTC, UnsungHero97 commented on src/containers/app/AppContainer.js
> +            <NavLink to={Routes.STUDIES} />
You'll want another `NavLink` so that it shows as a tab:

```
<NavLink to={Routes.STUDIES} />
<NavLink to={Routes.STUDIES}>Studies</NavLink>
```

2019-12-05 21:42 UTC, UnsungHero97 commented on src/containers/studies/StudiesActions.js
> +
You need this at the top:

```
/*
 * @flow
 */
```

2019-12-05 21:42 UTC, UnsungHero97 commented on src/containers/studies/StudiesContainer.js
> +    getStudies,
Please sort alphabetically.

2019-12-05 21:42 UTC, UnsungHero97 commented on src/containers/studies/StudiesContainer.js
> +  formatStudy = (study: Map) => ({
I don't think this is necessary.

2019-12-05 21:42 UTC, UnsungHero97 commented on src/containers/studies/StudiesContainer.js
> +              Sorry, no studies were found. Please try refreshing the page, or contact support.
Indent.

2019-12-05 21:42 UTC, UnsungHero97 commented on src/containers/studies/StudiesContainer.js
> +  studiesReqState: state.getIn(['studies', GET_STUDIES, 'requestState']),
Please use the following pattern:

```
[GET_STUDIES]: state.getIn(['studies', GET_STUDIES, 'requestState'])
// or...
requestStates: {
  [GET_STUDIES]: state.getIn(['studies', GET_STUDIES, 'requestState'])
}
```

2019-12-05 21:42 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +  getStudiesWorker,
Please sort alphabetically.

2019-12-05 21:42 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +function* getStudiesPermissionsWorker(action: SequenceAction) {
I don't think any of the `getStudiesPermissions`-related things need to exist. None of it is used in the old app. Please remove.

2019-12-05 21:42 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +function* getStudiesPermissionsWatcher() {
Please remove.

2019-12-05 21:42 UTC, UnsungHero97 commented on src/containers/studies/StudiesActions.js
> +const getStudiesPermissions: RequestSequence = newRequestSequence(GET_STUDIES_PERMISSIONS);
I don't think any of the `getStudiesPermissions`-related things need to exist. None of it is used in the old app. Please remove.

2019-12-05 21:42 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +    const entitySetId = yield call(EntitySetsApi.getEntitySetId, ENTITY_SETS.CHRONICLE_STUDIES);
Let's chat.

2019-12-05 21:42 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +    );
Yes, let's use `getEntitySetData` for now. We can get more fancy in the future.

2019-12-05 21:45 UTC, giuliacampana commented on src/components/StudyCard.js
> +      <Card onClick={(event) => handleCardClick(event)} data-study-id={study.id}>
Oops, sorry. My bad!

2019-12-06 04:16 UTC, solomontang requested changes

2019-12-06 04:16 UTC, solomontang commented on generateEntitySets.js
> +// generateEntitySets();
These comments and the lack exports suggest this file does not need to be committed. Please remove.

2019-12-06 04:16 UTC, solomontang commented on src/components/StudyCard.js
> +  font-size: 14px;
There are lots of nice plugins you can find for your IDE of choice that will do this for you.

2019-12-06 04:16 UTC, solomontang commented on src/components/StudyCard.js
> +/* stylelint-disable value-no-vendor-prefix, property-no-vendor-prefix */
You should not have to apply this rule. I am using webkit prefixes just fine without any linting errors

2019-12-06 04:16 UTC, solomontang commented on src/components/StudyCard.js
> +      <Card onClick={(event) => handleCardClick(event)} data-study-id={study.id}>
I like to call it skewer-case but kebabs are tasty

2019-12-06 04:16 UTC, solomontang commented on src/containers/studies/StudiesContainer.js
> +  }
Remove unused code

2019-12-06 04:16 UTC, solomontang commented on src/utils/constants/DataModelConstants.js
> +export const GENERAL_STRING_ID_PT_ID = 'ee3a7573-aa70-4afb-814d-3fad27cda988';
Probably not good to hard code this value...

2019-12-06 21:22 UTC, UnsungHero97 requested changes

2019-12-06 21:22 UTC, UnsungHero97 commented on package.json
> +    "prop-types": "^15.7.2",
@anzioka please remove the `prop-types` dependency.

2019-12-06 21:22 UTC, UnsungHero97 commented on src/components/StudyCard.js
> +/* stylelint-disable */
This should be `stylelint-enable`.

2019-12-06 21:22 UTC, UnsungHero97 commented on src/components/StudyCard.js
> +      <Card onClick={this.handleCardClick} data-study-id={study.id}>
The type annotation shows that `study` is a `Map`, so this should be `study.get('id')`.

2019-12-06 21:22 UTC, UnsungHero97 commented on src/components/StudyCard.js
> +              {study.name}
The type annotation shows that study is a Map, so this should be `study.get('name')`.

2019-12-06 21:22 UTC, UnsungHero97 commented on src/components/StudyCard.js
> +            {study.description}
The type annotation shows that study is a Map, so this should be `study.get('description')`.

2019-12-06 21:22 UTC, UnsungHero97 commented on src/containers/studies/StudiesActions.js
> +const GET_STUDIES_PERMISSIONS :'GET_STUDIES_PERMISSIONS' = 'GET_STUDIES_PERMISSIONS';
`GET_STUDIES_PERMISSIONS` and `getStudiesPermissions` is not used anywhere. Please remove.

2019-12-06 21:22 UTC, UnsungHero97 commented on src/core/edm/EDMSagas.js
> +    yield put(getAllEntitySetIds.failure(action.id, error));
Add a log for the error:

```
  catch (error) {
    LOG.error(action.type, error);
    yield put(getAllEntitySetIds.failure(action.id, error));
  }
```

2019-12-06 21:22 UTC, UnsungHero97 commented on src/core/edm/EDMSagas.js
> +}
`getAllEntitySetIdsWorker` is called in `initializeApplication`. It's good practice to have workers return something if they are directly called by other workers. Take a look at `getEntityDataModelTypesWorker` above and how it returns `workerResponse` at the end.

```
function* getAllEntitySetIdsWorker(action :SequenceAction) :Generator<*, *, *> {

  const workerResponse :Object = {};

  try {
    ...
  }
  catch (error) {
    LOG.error(action.type, error);
    workerResponse.error = error;
    yield put(getAllEntitySetIds.failure(action.id, error));
  }
  finally {
    ...
  }

 return workerResponse;
}
```

2019-12-06 21:22 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +    yield put(getStudies.failure(action.id, error));
Add a log for the error:

```
  catch (error) {
    LOG.error(action.type, error);
    yield put(getStudies.failure(action.id, error));
  }
```

2019-12-06 21:22 UTC, UnsungHero97 commented on src/containers/studies/StudiesReducer.js
> +      const seqAction = action;
```
import type { SequenceAction } from 'redux-reqseq';
...
const seqAction :SequenceAction = action;
```

2019-12-06 21:22 UTC, UnsungHero97 commented on src/containers/studies/StudiesContainer.js
> +});
Here's how I order these:

```
{
  // first are shorthand properties, i.e. keys without values
  thing,
  // next are computed properties
  [THING]: state.get(THING),
  // last are regular properties
  thingies: state.get('thingies'),
};
```

2019-12-06 21:22 UTC, UnsungHero97 commented on src/containers/studies/StudiesContainer.js
> +  studiesReqState: state.getIn(['studies', GET_STUDIES, 'requestState']),
@anzioka ping

2019-12-06 21:22 UTC, UnsungHero97 commented on src/containers/app/AppSagas.js
> +      call(getAllEntitySetIdsWorker, getAllEntitySetIds()),
You should fail the saga if `getAllEntitySetIds` fails.

2019-12-06 21:22 UTC, UnsungHero97 commented on src/containers/studies/StudiesContainer.js
> +  });
I don't think this is necessary for 2 reasons:
  1. you're effectively doing `study.toJS()`, which should be avoided
  2. doing this defeats the purpose of using `immutable.js`

I recommend removing `formatStudy` and using `study` directly as an immutable map.

2019-12-06 22:01 UTC, anzioka commented on src/containers/app/AppSagas.js
> +      call(getAllEntitySetIdsWorker, getAllEntitySetIds()),
Modified to return an error in an object if saga fails

2019-12-09 21:53 UTC, UnsungHero97 approved these changes

2019-12-09 22:06 UTC, solomontang approved these changes

2019-12-09 22:06 UTC, solomontang commented on .gitignore
> +generateEntitySets.js
Please don't check in any changes to .gitignore if they're only meant for your local environment. You can imagine how this file would quickly become bloated if everyone did this. Please remove.

If you're using generateEntitySets to behaviorally test your components and functions, you might as well formalize the process and make it part of your testing suite instead of commenting it out.

2019-12-09 22:06 UTC, solomontang commented on package.json
> +    "prop-types": "^15.7.2",
This is still not resolved

2019-12-09 22:06 UTC, solomontang commented on src/components/StudyCard.js
> +/* stylelint-disable value-no-vendor-prefix, property-no-vendor-prefix */
turns out this might just be a problem with my ide. carry on

2019-12-09 22:06 UTC, solomontang commented on src/containers/studies/StudiesContainer.js
> +  }
Moving forward, you should avoid checking in code for future features. Not necessary to resolve now. just thought i'd mention it.

2019-12-09 22:06 UTC, solomontang commented on src/containers/studies/components/StudyCard.js
> +    const numParticipants = 3; // TODO: change this to the actual number of participants
No change necessary for this PR. But again, try not to check in code that is not intended for production

2019-12-09 22:33 UTC, merged