Task/apps 2375 submit TUD survey
methodic-labs/chronicle-web pull request #319
Opened 2020-10-12 17:26 UTC by anzioka

PR:
Submit TUD survey

2020-10-12 23:49 UTC, UnsungHero97 requested changes

2020-10-12 23:49 UTC, UnsungHero97 commented on src/containers/shared/SubmissionSuccessful.js
> +    </p>
Not required for this pr, but please start using the LUK `Typography` components.

2020-10-12 23:49 UTC, UnsungHero97 commented on src/containers/shared/SubmissionSuccessful.js
> +  contentText: 'Thank you for participating in survey. Your responses have been successfully recorded'
Missing period at the end.

2020-10-12 23:49 UTC, UnsungHero97 commented on src/containers/shared/BasicModal.js
> +      </p>
Use `children` instead of a prop.

2020-10-12 23:49 UTC, UnsungHero97 commented on src/containers/tud/TimeUseDiaryContainer.js
> +            title="Submission Error" />
Take advantage of `children` instead of passing a prop.

```
<BasicModal ...>
  <p>An error occurred while trying to submit survey. Please try again later.</p>
</BasicModal>
```

2020-10-12 23:49 UTC, UnsungHero97 commented on src/containers/tud/TimeUseDiaryContainer.js
> +            ? <SubmissionSuccessful contentText={successText} />
Use `children` instead of a prop.

2020-10-12 23:49 UTC, UnsungHero97 commented on src/utils/api/ChronicleApi.js
> + * POST chronicle/study/<studyId>/<participantId>/time-use-diary
Does this endpoint exist yet?

2020-10-12 23:49 UTC, UnsungHero97 commented on src/core/sagas/Sagas.js
> +    fork(TimeUseDiarySagas.submitTudDataWatcher)
Trailing comma, please.

2020-10-12 23:49 UTC, UnsungHero97 commented on src/containers/tud/constants/GeneralConstants.js
> +  [WAKE_UP_COUNT]: 'Wake up at night'
Why not do `[PROPERTY_CONSTS.DEVICE]` and avoid lines 5 - 34?

2020-10-12 23:55 UTC, anzioka commented on src/utils/api/ChronicleApi.js
> + * POST chronicle/study/<studyId>/<participantId>/time-use-diary
Not in prod, but there is a PR in the pipeline

2020-10-13 00:25 UTC, bergieboy submitted a review, later dismissed

2020-10-13 00:25 UTC, bergieboy commented on src/containers/shared/BasicModal.js
> +  title :string;
sort

2020-10-13 00:25 UTC, bergieboy commented on src/containers/shared/SubmissionSuccessful.js
> +    font-size: 15px;
sort

2020-10-13 00:25 UTC, bergieboy commented on src/containers/tud/TimeUseDiarySagas.js
> +      formData
sort

2020-10-13 00:33 UTC, bergieboy approved these changes

2020-10-14 23:58 UTC, UnsungHero97 approved these changes

2020-10-14 23:58 UTC, merged