Task/apps 2471 tud data download dashboard
methodic-labs/chronicle-web pull request #377
Opened 2020-11-11 00:49 UTC by anzioka

PR:
A basic dashboard for retrieving time use diary submissions constrained by a date range, and creating a csv file for all submissions by day. 

The new Time Use Diary tab is only visible for studies that are associated with the Time Use Diary survey entity.

<img width="1129" alt="Screen Shot 2020-11-10 at 4 21 36 PM" src="https://user-images.githubusercontent.com/15723547/98750190-26da0b80-2372-11eb-848f-a8a7b984aa82.png">

no submissions for specified date range
<img width="1153" alt="Screen Shot 2020-11-10 at 4 21 23 PM" src="https://user-images.githubusercontent.com/15723547/98750207-32c5cd80-2372-11eb-9e03-de4e431a3c64.png">

csv file snapshots:
<img width="818" alt="Screen Shot 2020-11-10 at 2 18 05 PM" src="https://user-images.githubusercontent.com/15723547/98751182-76213b80-2374-11eb-9d4e-0a2ca3d2ada3.png">

<img width="854" alt="Screen Shot 2020-11-10 at 2 17 04 PM" src="https://user-images.githubusercontent.com/15723547/98751225-8a653880-2374-11eb-8765-14974f636891.png">

2020-11-17 17:12 UTC, UnsungHero97 requested changes

2020-11-17 17:12 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +  }
Missing `finally` block.

2020-11-17 17:12 UTC, UnsungHero97 commented on src/containers/tud/TimeUseDiarySagas.js
> +    const addressesESID = yield select(selectEntitySetId(ADDRESSES_ES_NAME));
No change required. Depending on the structure of your redux store, you could use `selectEntitySets` from `lattice-utils`.

2020-11-17 17:36 UTC, UnsungHero97 submitted a review, later dismissed

2020-11-18 21:51 UTC, bergieboy requested changes

2020-11-18 21:51 UTC, bergieboy commented on src/containers/studies/StudiesReducer.js
> +      });
You added `finally` block to Saga, but not here. So should we add:
```
.setIn([GET_TIME_USE_DIARY_STUDIES, action.id], action)
```
to `REQUEST`, and:
```
.deleteIn([GET_TIME_USE_DIARY_STUDIES, action.id])
```
to `FINALLY`?

2020-11-18 21:51 UTC, bergieboy commented on src/containers/studies/StudiesSagas.js
> +      const studyEntityKeyIds = authorizedStudies.map((study) => study.getIn([OPENLATTICE_ID_FQN, 0]));
use `getEntityKeyId` from `lattice-uitils`

2020-11-18 21:51 UTC, bergieboy commented on src/containers/study/StudyDetailsContainer.js
> +            render={() => <TimeUseDiaryDashboard studyEKID={getEntityKeyId(study)} studyId={studyUUID} />} />
`studyEKID` is already defined above. No need to `getEntityKeyId` twice.

2020-11-18 21:51 UTC, bergieboy commented on src/containers/tud/TimeUseDiaryReducer.js
> +      });
`finally` blocks are in sagas, but no `FINALLY` cases here.

2020-11-18 21:51 UTC, bergieboy commented on src/containers/tud/TimeUseDiarySagas.js
> +} = ENTITY_SET_NAMES;
sort

2020-11-18 21:51 UTC, bergieboy commented on src/containers/tud/TimeUseDiarySagas.js
> +    const participantEKIDs :UUID[] = participantsRes.data.map((entity) => getEntityKeyId(entity));
```
const participantEKIDs :UUID[] = participantsRes.data.map(getEntityKeyId);
```

2020-11-18 21:51 UTC, bergieboy commented on src/containers/tud/components/SearchPanel.js
> +`;
sort

2020-11-18 21:51 UTC, bergieboy commented on src/containers/tud/components/SearchPanel.js
> +  DatePicker
sort imports

2020-11-18 21:51 UTC, bergieboy commented on src/containers/tud/components/SummaryListComponent.js
> +) => (
sort

2020-11-18 22:32 UTC, anzioka commented on src/containers/tud/TimeUseDiarySagas.js
> +    const participantEKIDs :UUID[] = participantsRes.data.map((entity) => getEntityKeyId(entity));
awesome!

2020-11-18 22:38 UTC, anzioka commented on src/containers/studies/StudiesReducer.js
> +      });
Agreed.

2020-11-18 23:16 UTC, bergieboy approved these changes

2020-11-18 23:17 UTC, UnsungHero97 approved these changes

2020-11-18 23:18 UTC, merged