Feature/apps 1591 create study modal
methodic-labs/chronicle-web pull request #4
Opened 2019-12-09 23:46 UTC by anzioka

Created an ActionModal for creating a new study. Functionality to create study will come later.

<img width="695" alt="create_study" src="https://user-images.githubusercontent.com/15723547/70482679-fff8c280-1a9a-11ea-98d7-f2fe283a0278.png">

2019-12-10 01:31 UTC, UnsungHero97 requested changes

2019-12-10 01:31 UTC, UnsungHero97 commented on package.json
> +    "lattice-fabricate": "^0.7.2",
Please use `~` instead of `^`.

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/StudiesActions.js
> +  CREATE_STUDY,
Please sort.

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/StudiesContainer.js
> +}
You need a semi-colon here.

```
type State = {
  ...
}; <- semicolon
```

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/StudiesReducer.js
> +  [CREATE_STUDY]: { requestState: RequestStates.STANDBY },
Please sort.

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyForm.js
> +}
Missing semicolon.

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyForm.js
> +  },
You should wrap this in another layer of `properties` because it'll render nicer in the modal. I'll show you.

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +const initialFormDataState :Object = {
If you're pulling out initial state into a constant, why is it not being used anywhere?

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +      data: { ...initialFormDataState },
You don't need to spread. `data: initialFormDataState` is identical. Also, I recommend removing `initialFormDataState` and just setting the state here, unless you plan on reusing `initialFormDataState` somewhere else.

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +}
Missing semicolon.

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +  isSubmitting :boolean;
We've moved away from using booleans to indicate request state. Please use a proper `RequestState`, which is probably `CREATE_STUDY`.

Separately, from what I can see, `isSubmitting` isn't real. It is not passed in from a parent component. Please double check this prop.

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +  }
Missing semicolon.

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +  handleOnCloseModal :Function;
The `:Function` type should be avoided. The annotation for this should be `() => void;`.

https://flow.org/en/docs/types/functions/#toc-function-type

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +`;
No change required.

This probably belongs in `src/components/modals`, similar to how `lattice-orgs` has it.

2019-12-10 01:31 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +          <span> Failed to create a new study. Please try again </span>
You need a period at the end of `Please try again.`.

2019-12-10 02:12 UTC, solomontang commented on src/containers/studies/components/CreateStudyForm.js
> +  },
You should also the data processing utils to handle your data. Unfortunately the documentation isn't very good but there is a working example of how to set up the schema and such on storybook

https://openlattice.github.io/lattice-fabricate/?path=/story/form--data-processing-w-edits-delete

2019-12-10 02:12 UTC, solomontang commented on src/containers/studies/components/CreateStudyModal.js
> +  }
You only need to supply an `onChange` if you want to execute side effects (this that occur outside of updating form field states). Since this callback function is only controlling the state which is already managed by the Form component internally, all this will do is incur extraneous render cycles.

You can track this by dropping a `console.log` in the `render` method of `CreateStudyForm` and you should see that it is triggered on every field update. By omitting this function, you should still have the same behavior without re-rendering the entire parent component.

2019-12-10 02:12 UTC, solomontang commented on src/containers/studies/components/CreateStudyForm.js
> +      uiSchema={uiSchema} />
Fabricate is built on top of the `react-jsonschema-form` library and for the basics, you can use their website for documention. Our internal widgets try to match what is provided out of the box from this library. However, you're probably going to need a rundown of how the `DataProcessingUtils` work.

You do not need to provide an `onChange` prop to the `Form` if you are not executing any side effects.
https://react-jsonschema-form.readthedocs.io/en/latest/#form-initialization

Please provide an onSubmit
https://react-jsonschema-form.readthedocs.io/en/latest/#form-initialization

I suspect CreateStudyForm will not need to prepopulate any data and thus the `formData` prop can also be omitted.
https://react-jsonschema-form.readthedocs.io/en/latest/#form-initialization

2019-12-12 01:42 UTC, anzioka commented
![modal](https://user-images.githubusercontent.com/15723547/70675132-29515400-1c3d-11ea-93a6-36babefdf8c2.gif)

Added functionality to create a new study by leveraging fabricate's DataProcessingUtils. The shiny new study form includes input validation (name and email are required fields).

2019-12-12 01:48 UTC, anzioka commented
<img width="1007" alt="Screen Shot 2019-12-11 at 5 44 08 PM" src="https://user-images.githubusercontent.com/15723547/70675570-5eaa7180-1c3e-11ea-9584-391f7f43782c.png">

2019-12-12 03:21 UTC, solomontang requested changes

2019-12-12 03:21 UTC, solomontang commented on src/containers/studies/StudiesContainer.js
> +    actions.resetRequestState(CREATE_STUDY);
Judging from when this action is dispatched, I suspect you might have a visual bug.

As the form is fading out, does the modal view also reset back to its standby state with an empty form instead of the success message? This is probably happening since the state is reset before the animation can finish. Ideally, you would couple the `resetRequestState` when the contents of the Modal are unmounted.

2019-12-12 03:21 UTC, solomontang commented on src/containers/studies/components/CreateStudyForm.js
> +  });
Yay hooks!

This call to `useCallback` does not have a dependency list. This means that the callback is not really memoized since it will change upon every render. I recommend removing `useCallback` until you actually observe performance consequences or bad render cycles.

I suspect you should have an eslint error if you have installed the necessary plugins. You should do your best to heed the linter when doing anything Hook related as it will stop an entire class of bugs ahead of time.

References:
https://reactjs.org/docs/hooks-reference.html#usecallback
https://www.npmjs.com/package/eslint-plugin-react-hooks

2019-12-12 03:21 UTC, solomontang commented on src/containers/studies/components/CreateStudyModal.js
> +  });
Same as the previous comment about `useCallback`. Either provide the exhaustive dependency array, or don't use `useCallback`.

2019-12-12 18:57 UTC, solomontang commented on src/containers/studies/components/CreateStudyForm.js
> +  });
As a follow-up clarification, lifecycle methods are concerned with when some change should occur. `componentDidMount`, `componentDidUpdate`, `componentWillUnmount` are event driven. Often times, this leads to repeated code across different lifecycle methods and manual checks for equality/change.

Hooks on the other hand are concerned with state synchronization. When you provide a dependency list, you're declaring that your effect/memo/callback is in sync with those specific items by reference equality. By not providing a dependency list, you're saying that your effect/memo/callback is in sync with everything and will update on every render. Similarly, providing an empty dependency list means your hook synchronizes with nothing and will only be run once.

In short, using hooks can be beneficial and fun, but it does take changing the way you have previously approached React.

2019-12-17 07:07 UTC, anzioka commented on src/containers/studies/StudiesContainer.js
> +    actions.resetRequestState(CREATE_STUDY);
You are right! There was a visual bug, though almost unnoticeable. The success message was rendered but on closing the modal an empty form would be temporarily rendered before the modal closed. I fixed the issue by calling resetRequestState before the modal was rendered (when the isVisible prop is set to true).

2019-12-17 07:11 UTC, UnsungHero97 requested changes

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +  };
This doesn't need to be a function, `requestStateComponents` can be a plain object.

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +};
Please sort the props alphabetically.

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +} from 'lattice-ui-kit';
You only need to split into multiple lines if there's 4 or more imports.

2019-12-17 07:11 UTC, UnsungHero97 commented on src/core/edm/EDMReducer.js
> +            .set('propertyTypesFqnIdMap', propertyTypesFqnIdMap.asImmutable())
You haven't defined this in `INITIAL_STATE`.

2019-12-17 07:11 UTC, UnsungHero97 commented on src/core/edm/EDMReducer.js
> +              const typeFqn :FullyQualifiedName = new FullyQualifiedName(propertyType.type);
Use the shorter `FQN` annotation:

```
import type { FQN } from 'lattice';
const fqn :FQN = new FullyQualifiedName(propertyType.type);
```

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyForm.js
> +    const assocationEntityData = {};
This is misspelled; should be `associationEntityData`.

2019-12-17 07:11 UTC, UnsungHero97 commented on src/core/sagas/data/DataSagas.js
> +      .setAssociations(value.assocationEntityData)
This is misspelled; should be `associationEntityData`.

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyForm.js
> +      assocationEntityData
This is misspelled; should be `associationEntityData`.

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyForm.js
> +      [getPageSectionKey(1, 1), getEntityAddressKey(0, CHRONICLE_STUDIES, STUDY_ID)], uuid());
Please fix formatting:

```
newFormData = setIn(
  newFormData,
  [getPageSectionKey(1, 1), getEntityAddressKey(0, CHRONICLE_STUDIES, STUDY_ID)],
  uuid(),
);
```

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyForm.js
> +};
Why is this empty?

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/StudiesContainer.js
> +
Please remove empty line.

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/StudiesReducer.js
> +        SUCCESS: () => state.setIn([CREATE_STUDY, 'requestState'], RequestStates.SUCCESS),
On success, you need to update state with the new study so that it shows up in the list.

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +  let response = {};
This doesn't need to be a `let`. It can be a `const` on line 66.

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +    LOG.error('caught exception in createStudy()', error);
This should be `LOG.error(action.type)`. Please follow the patterns consistently.

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +  actions:{
There should be a space before the colon... `actions :{`

2019-12-17 07:11 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
> +    createStudy,
This action is not used in the component.

2019-12-17 17:16 UTC, UnsungHero97 requested changes

2019-12-17 17:16 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
>      resetRequestState :RequestSequence
`resetRequestState` is also not used anywhere. Please remove.

2019-12-17 17:16 UTC, UnsungHero97 commented on src/containers/studies/components/CreateStudyModal.js
>  });
Given that the component doesn't use any actions, it's safe to remove `mapDispatchToProps` entirely.

2019-12-17 19:32 UTC, UnsungHero97 requested changes

2019-12-17 19:32 UTC, UnsungHero97 commented on package.json
> +    "eslint-plugin-react-hooks": "^2.3.0",
Please use `~` instead of `^`.

2019-12-17 19:32 UTC, UnsungHero97 commented on src/containers/studies/StudiesContainer.js
> +    actions.resetRequestState(CREATE_STUDY);
Why do you trigger this action before the modal opens?

2019-12-17 19:32 UTC, UnsungHero97 commented on src/containers/studies/StudiesReducer.js
> +          const study = state.getIn(['studies', studyUUID], Map());
I'd be surprised if this is actually working. In the worker, you have:

```
yield put(createStudy.success(id));
```

This means `action.value` is equal to `{}` and `studyUUID` will be undefined.

Separately, why are you getting the new study from state? It's a new study, which means it won't be in state, which means you'll always be storing an empty map below.

2019-12-17 19:32 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +  const { id, value } = action;
Please move this inside the `try` block.

2019-12-17 19:38 UTC, solomontang commented on package.json
> +    "eslint-plugin-react-hooks": "^2.3.0",
Pin the version to patch by using `~` instead of `^`

2019-12-17 19:38 UTC, solomontang commented on src/containers/studies/StudiesContainer.js
>      goToRoute: RoutingActions.goToRoute,
You should get in the habit of sorting. We're probably going to be using prettier soon so this will be less of an ordeal in the future.

2019-12-17 19:53 UTC, solomontang commented on src/containers/studies/StudiesContainer.js
> +    actions.resetRequestState(CREATE_STUDY);
I suspect this is to clear any previous lingering request states. Before, he was clearing on close but since it was being called in the parent container, it was causing flickering when then modal was transitioning out. 

Ideally, you would co-locate as much of the logic relating to the contents of your modal all in one place. The Modal will unmount its children when the transition is complete. So as long as the contents of the modal are responsible for their own cleanup, there won't be any issues.

But this seems to be the next best way.

2019-12-17 20:36 UTC, anzioka commented on src/containers/studies/StudiesContainer.js
>      goToRoute: RoutingActions.goToRoute,
Ok, sorted.

2019-12-17 20:39 UTC, anzioka commented on src/containers/studies/StudiesReducer.js
> +          const study = state.getIn(['studies', studyUUID], Map());
I fixed this.

2019-12-17 20:45 UTC, anzioka commented on src/containers/studies/StudiesContainer.js
> +    actions.resetRequestState(CREATE_STUDY);
You are right @solomontang. After a SUCCESS/ FAILURE success state, opening the modal a second time would not render the form component, that's why I reset the state before the modal opens.

2019-12-19 16:52 UTC, closed without merging

2019-12-19 16:54 UTC, anzioka commented
Merged  feature/APPS-1592-create-study-details-page with this branch.