associate new study with notifications after successfully creating study
methodic-labs/chronicle-web pull request #422
Opened 2020-12-08 18:35 UTC by anzioka

PR:
bug fix when creating a new study with notifications enabled

2020-12-08 18:42 UTC, UnsungHero97 requested changes

2020-12-08 18:42 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +function* getNotificationsEntityWorker(action :SequenceAction) :Generator<*, *, *> {
Please switch to `:Saga<WorkerResponse>`.

2020-12-08 21:01 UTC, UnsungHero97 approved these changes

2020-12-09 18:46 UTC, solomontang approved these changes

2020-12-09 18:47 UTC, merged