disable delete legacy data for unauthorized user
methodic-labs/chronicle-web pull request #744
Opened 2021-06-28 04:31 UTC by anzioka

2021-06-28 18:13 UTC, UnsungHero97 requested changes

2021-06-28 18:13 UTC, UnsungHero97 commented on src/core/permissions/PermissionsReducer.js
> +          .setIn([GET_DELETE_PERMISSION, REQUEST_STATE], RequestStates.PENDING)
```suggestion
          .setIn([GET_DELETE_PERMISSION, REQUEST_STATE], RequestStates.FAILURE)
```

2021-06-28 18:13 UTC, UnsungHero97 commented on src/core/permissions/PermissionsReducer.js
> +          .setIn([HAS_DELETE_PERMISSION, HAS_DELETE_PERMISSION], true),
```suggestion
          .setIn([studyId, HAS_DELETE_PERMISSION], true),
```

2021-06-28 19:07 UTC, UnsungHero97 submitted a review, later dismissed

2021-06-29 16:53 UTC, solomontang submitted a review, later dismissed

2021-07-07 17:27 UTC, UnsungHero97 approved these changes, later dismissed

2021-07-07 17:36 UTC, giuliacampana approved these changes, later dismissed

2021-07-07 18:00 UTC, solomontang submitted a review, later dismissed

2021-07-07 18:23 UTC, UnsungHero97 approved these changes

2021-07-07 18:35 UTC, giuliacampana approved these changes

2021-07-07 18:45 UTC, solomontang approved these changes

2021-07-07 18:46 UTC, merged