Feature/metadata
methodic-labs/chronicle-web pull request #86
Opened 2020-05-24 01:24 UTC by jokedurnez

Adding metadata information for monitoring.

Depends on https://github.com/openlattice/chronicle-server/pull/86, so leaving as draft for now.

![image](https://user-images.githubusercontent.com/7630327/85086891-cfec5380-b190-11ea-98a1-a95421281382.png)

2020-06-19 02:03 UTC, anzioka reviewed
looks good. how do you feel about centering daysCollected row content though?

<img width="929" alt="Screen Shot 2020-06-18 at 7 02 30 PM" src="https://user-images.githubusercontent.com/15723547/85089008-49d30b80-b196-11ea-8401-abf11629928b.png">

```
const CellContent = styled.div`
  display: flex;
  font-size: 15px;
  font-weight: 300;
  overflow: hidden;
  padding: 0 5px;
  justify-content: ${(props) => (props.centerContent ? 'center' : 'flex-start')}`;
```

Then 

```
<CellContent centerContent>
   { numDays }
</CellContent>
```

2020-06-19 19:25 UTC, UnsungHero97 requested changes

2020-06-19 19:25 UTC, UnsungHero97 commented on src/containers/study/utils/tableHeaders.js
> +} = PROPERTY_TYPE_FQNS;
Formatting:

```
const {
  DATE_FIRST_PUSHED, 
  DATE_LAST_PUSHED, 
  EVENT_COUNT,
  PERSON_ID, 
} = PROPERTY_TYPE_FQNS;
```

2020-06-19 19:25 UTC, UnsungHero97 commented on src/containers/study/utils/tableHeaders.js
> +      textAligh: 'center',
`textAlign`

2020-06-19 19:25 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +  // NOTIFICATION_DESCRIPTION,
Please remove if unused.

2020-06-19 19:25 UTC, UnsungHero97 commented on src/containers/studies/StudiesReducer.js
> +          const { associationKeyIds, participantsEntitySetName } = seqAction.value;
`associationKeyIds` is not passed on success...

```
getParticipantsMetadata.success(action.id, { neighborKeyIds, participantsEntitySetName })
```

2020-06-19 19:25 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +    if (response.error) throw response.error;
If the metadata request is the only request that fails, that means we can still show participants in the table, just without metadata. However, if you throw here, the the entire saga will fail, which means the participants table will be empty.

As such, I don't think you should throw here. I think it's better to show participants without metadata vs no participants at all.

2020-06-19 19:25 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +    const metadata :Map = response.data;
Assuming you update the code above and do not throw, then `response.data` will be undefined. You'll need to add a default here.

```
const metadata :Map = response.data || Map();
```

2020-06-19 19:25 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +      const datesLogged = metadata.getIn([id, DATE_LOGGED]);
Similarly, assuming `metadata` is empty, you should pass a default value for this `.getIn()`.

```
const datesLogged :List = metadata.getIn([id, DATE_LOGGED], List());
const count :number = datesLogged.count();
```

2020-06-19 19:25 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +    participants = participants.map((participant, id) => {
Please rename `id` to `participantEKID` or `participantEntityKeyId`.

2020-06-19 19:25 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +    }); // required by LUK table
Please move the `// required by LUK table` comment to be after the `.set('id', [id]);`, which is the actual LUK requirement.

2020-06-19 22:22 UTC, jokedurnez commented on src/containers/studies/StudiesSagas.js
> +      const datesLogged = metadata.getIn([id, DATE_LOGGED]);
Done.  Out of curiosity, why `count()` and not `.size`?

2020-06-19 22:58 UTC, anzioka requested changes

2020-06-19 22:58 UTC, anzioka commented on src/containers/studies/StudiesActions.js
> +
`GET_PARTICIPANTS_METADATA`

2020-06-19 22:58 UTC, anzioka commented on src/containers/studies/StudiesSagas.js
> +  DATE_LOGGED,
missing from PROPERTY_TYPE_FQNS object

2020-06-19 22:58 UTC, anzioka commented on src/containers/study/components/ParticipantRow.js
> +  justify-content: ${(props) => (props.centerContent ? 'center' : 'flex-start')}
missing `;` at the end of this line

2020-06-20 00:08 UTC, UnsungHero97 commented on src/containers/studies/StudiesSagas.js
> +      const datesLogged = metadata.getIn([id, DATE_LOGGED]);
https://github.com/immutable-js/immutable-js/pull/1560

2020-06-20 00:21 UTC, UnsungHero97 requested changes

2020-06-20 00:21 UTC, UnsungHero97 commented on src/containers/studies/StudiesReducer.js
> +    }
I don't see `neighborKeyIds` or the `GET_PARTICIPANTS_METADATA ` request state being used in any component, so I'm pretty sure all of the changes to this file can be removed.

2020-06-20 00:24 UTC, UnsungHero97 approved these changes

2020-06-20 00:25 UTC, merged

2020-06-20 00:25 UTC, anzioka approved these changes