Task/apps 2011 implement questionnaire submission/download responses
methodic-labs/chronicle-web pull request #97
Opened 2020-05-26 19:11 UTC by anzioka

PR:
Implement functionality to submit responses to a questionnaire
Display participant's responses to a questionnaire
Download questionnaire responses.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15723547/82940108-3347e480-9f49-11ea-922f-2147fc972023.gif)

Mobile view
<img width="489" alt="submit" src="https://user-images.githubusercontent.com/15723547/82939770-a866ea00-9f48-11ea-9c23-c243a6f115cd.png">

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/15723547/82940579-eb758d00-9f49-11ea-9dc0-517e2e633085.gif)

2020-05-26 19:27 UTC, UnsungHero97 requested changes

2020-05-26 19:27 UTC, UnsungHero97 commented on flow-typed/npm/papaparse.js.flow
> +}
Use flow-typed to create the stub.

```
flow-typed create-stub papaparse
```

2020-05-26 19:27 UTC, UnsungHero97 commented on flow-typed/npm/file-saver_v2.x.x.js
> +declare module "file-saver" {
Did you create this using `flow-typed`?

```
flow-typed install file-saver@2
```

2020-05-26 19:35 UTC, anzioka commented on flow-typed/npm/papaparse.js.flow
> +}
Didn't know `create-stub` was a thing. Thanks!

2020-05-26 19:37 UTC, anzioka commented on flow-typed/npm/file-saver_v2.x.x.js
> +declare module "file-saver" {
Yes, I did.

2020-06-05 00:39 UTC, giuliacampana submitted a review, later dismissed

2020-06-05 00:39 UTC, giuliacampana commented on flow-typed/npm/papaparse_vx.x.x.js
> +}
I think you probably don't need these.

2020-06-05 00:39 UTC, giuliacampana commented on src/containers/questionnaire/QuestionnaireSagas.js
> +    // console.log(response.data);
can remove this console.log.

2020-06-05 00:39 UTC, giuliacampana commented on flow-typed/npm/react-dom_vx.x.x.js
> +}
I think you don't need anything after line 18.

2020-06-09 17:50 UTC, UnsungHero97 requested changes

2020-06-09 17:50 UTC, UnsungHero97 commented on flow-typed/npm/react-dom_vx.x.x.js
> +}
`react-dom` actually exists so you can install it:

```
flow-typed install react-dom@16
```

https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-dom_v16.x.x/flow_v0.117.x-/react-dom_v16.x.x.js

2020-06-09 17:50 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireContainer.js
> +`;
`AppContainerWrapper` was fixed for mobile in LUK v0.31.0, so you can use it directly. It also will results in horizontal scrollbar for sizes less than 360:

<img width="380" alt="Screen Shot 2020-06-09 at 10 33 39 AM" src="https://user-images.githubusercontent.com/440299/84180921-25ac5780-aa3d-11ea-8dc0-60f45e1f03d9.png">

Separately, for outer / wrapper containers like this, `min-width` is not the right way to handle responsiveness. `min-width` will prevent the element from shrinking right around the `media.tablet` / `media.phone` widths, which will introduce horizontal scrollbars. Removing these will allow the element to resize correctly with the browser at all levels, and the existing value for `max-width` set on `AppContainerWrapper` will cap it on huge screens.

2020-06-09 17:50 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireContainer.js
> +  }
Same comment as above. `AppHeaderWrapper` is mobile-friendly, you don't need `min-width`. Additionally, `AppHeaderWrapper` already updates the padding on `media.phone`.

https://github.com/openlattice/lattice-ui-kit/blob/develop/src/layout/src/components/App/styled/AppHeaderInnerWrapper.js#L20

2020-06-09 17:50 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireContainer.js
> +  }
Same comment as above. `AppContentWrapper` is mobile-friendly.

https://github.com/openlattice/lattice-ui-kit/blob/develop/src/layout/src/components/App/styled/AppContentInnerWrapper.js#L24

2020-06-09 18:30 UTC, anzioka commented on src/containers/questionnaire/QuestionnaireContainer.js
> +`;
Thanks! That's helpful.

2020-06-09 18:54 UTC, anzioka commented on flow-typed/npm/react-dom_vx.x.x.js
> +}
I tried this but all I got was `Searching for 1 libdefs...` and nothing else.

2020-06-09 18:59 UTC, anzioka commented on flow-typed/npm/react-dom_vx.x.x.js
> +}
ah, now resolved. I needed to update flow-typed

2020-06-19 18:21 UTC, UnsungHero97 requested changes

2020-06-19 18:21 UTC, UnsungHero97 commented on src/core/edm/constants/FullyQualifiedNames.js
> +  TITLE_FQN: new FullyQualifiedName('ol.title')
`ol.title` is already defined above. `ol.description` is also a duplicate. It's fine to split up the FQNs based on feature, but please make sure there's no duplicates.

2020-06-19 18:21 UTC, UnsungHero97 commented on src/core/edm/constants/FullyQualifiedNames.js
> +  CRON_FQN: new FullyQualifiedName('ol.cron'),
You don't need `ol.cron` anymore, right?

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/study/components/DownloadQuestionnaireResponses.js
> +  /* eslint-disable max-len */
Don't disable here. You can fix the formatting easily to fit within `max-len` (which you've already done below):

```
const studyQuestionnaires = useSelector(
  (state) => state.getIn(['questionnaire', STUDY_QUESTIONNAIRES, studyEKID], Map())
);
```

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/study/components/DownloadQuestionnaireResponses.js
> +  }));
I don't know enough about hooks yet to know whether or not it's good practice to invoke `useSelector()` multiple times. However, it's a good idea to try to avoid this pattern because objects don't work well with `useEffect()`. 

You are not passing `requestStates` as part of the dependency array for `useEffect()`, which is good, but if you were to do that, it would be problematic because the `requestStates` object will be considered "new" on every render.

I recommend invoking `useSelector()` for each `RequestState`, especially since `RequestState`s are just strings.

```
const downloadRS :RequestState = useSelector((s) => s.getIn([...]));
const getQuestionnaireResponsesRS :RequestState = useSelector((s) => s.getIn([...]));
const getStudyQuestionnairesRS :RequestState = useSelector((s) => s.getIn([...]));
```

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireContainer.js
> +      <AppContentWrapper contentWidth={APP_CONTENT_WIDTH}>
You don't need `contentWidth={APP_CONTENT_WIDTH}` anymore. The `contentWidth` prop has been removed.

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireContainer.js
> +  }
Move this inside `<AppContentWrapper>` below.

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireContainer.js
> +            </div>
There's a handful of these types of components in the project already, with `margin-top` and `text-align` already set. Please refactor into a reusable component and use it here. As an example:

```
const Error = styled.div`
  ...
`;
const BasicErrorComponent = ({ children, message } :Props) => {
  ...
  return (
    <Error>{children || <span>{message}</span>}</Error>
  );
};
```

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireContainer.js
> +  }));
No change required. `lattice-utils` has a useful hook for this:

```
import { useRequestState } from 'lattice-utils';
const getQuestionnaireRS :?RequestState = useRequestState([APP, GET_QUESTIONNAIRE]);
const submitQuestionnaireRS :?RequestState = useRequestState([APP, SUBMIT_QUESTIONNAIRE]);
```

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireContainer.js
> +                { questionnaireDetails.getIn([DESCRIPTION_FQN, 0])}
Formatting.

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireSagas.js
> +function* getQuestionnaireWorker(action :SequenceAction) :Generator<*, *, *> {
```
import type { Saga } from '@redux-saga/core';
function* getQuestionnaireWorker(action :SequenceAction) :Saga<*> { ... }
```

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireSagas.js
> +      fromJS(response.data).forEach((value, key) => {
Please rename `value` and `key` to what they actually are, like you do in the previous search above.

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/QuestionnaireSagas.js
> +    });
It's a CSV... use `text/csv` as the mime type.

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/utils/formSchema.js
> +export default function createSchema(schemaProperties :Object, uiSchemaOptions :Object) {
The file name does not match. Rename this file to `createSchema.js` or something like that.

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/components/QuestionnaireForm.js
> +import { getSchemaProperties, getUiSchemaOptions } from '../utils/utils';
No change required. I have a style / file structure suggestion: use `index.js`

```
// src/.../QuestionnaireForm.js
import { createSchema, getSchemaProperties, getUiSchemaOptions } from '../utils';

// src/.../utils/index.js
const createSchema = () => { ... };
const getSchemaProperties = () => { ... };
const getUiSchemaOptions = () => { ... };
export {
  createSchema,
  getSchemaProperties,
  getUiSchemaOptions,
};
```

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/components/QuestionnaireForm.js
> +  });
This looks like a utility function. It should be defined outside of the component.

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/components/QuestionnaireForm.js
> +      <CardSegment vertical noBleed>
`CardSegment` now defaults to `vertical` being true; safe to remove the prop.

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/components/SubmissionStatus.js
> +        <p> Your responses were successfully submitted.</p>
Please don't add the spaces. Also, your formatting is not consistent; you have a space at the beginning, but not at the end.

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/questionnaire/utils/utils.js
> +};
No change required, just some feedback.

In this file, this function is the only one where you do not use `.withMutations()` followed by `.toJS()`, which I think is a good thing. Since you're only using immutable for the `mutator.setIn()` functionality, why not also just use plain objects + `setIn(object, [path])` in the other functions?

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/study/components/DownloadQuestionnaireResponses.js
> +          .map((answerId :UUID) => answersById.getIn([answerId, DATE_TIME_FQN, 0])).filter((val) => val);
Formatting. Please put `.filter()` on its own line.

```
const dates :List = answerIds
  .map()
  .filter();
```

2020-06-19 18:21 UTC, UnsungHero97 commented on src/containers/study/components/DownloadQuestionnaireResponses.js
> +  const [selectedQuestionnaire, setselectedQuestionnaire] = useState(null);
`setSelectedQuestionnaire`

2020-06-19 19:32 UTC, anzioka commented on src/containers/questionnaire/QuestionnaireContainer.js
> +                { questionnaireDetails.getIn([DESCRIPTION_FQN, 0])}
space before the closing curly brackets on l 115? @UnsungHero97

2020-06-19 21:11 UTC, UnsungHero97 submitted a review, later dismissed

2020-06-19 21:11 UTC, UnsungHero97 commented on src/containers/shared/BasicErrorComponent.js
> +  message ?:string
Missing `;`.

2020-06-19 21:11 UTC, UnsungHero97 commented on src/containers/shared/BasicErrorComponent.js
> +}
Missing `;`.

2020-06-19 22:33 UTC, UnsungHero97 approved these changes

2020-06-19 22:33 UTC, merged